check:
  image: golang:1.10
  before_script:
    - mkdir -p $GOPATH/src
    - >
      cd $GOPATH &&
      curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh |
      bash -s v1.6.1
    - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  script:
    - mkdir -p $GOPATH/src/gitlab.com/vectorup
    - ln -s ${CI_PROJECT_DIR} $GOPATH/src/gitlab.com/vectorup/asset-pb
    - cd $GOPATH/src/gitlab.com/vectorup/asset-pb
    - dep ensure
    - make check-style
    - make lint
    - make test
