repos:
- repo: local
  hooks:
    - id: gofmt-check
      entry: ./hooks/check-grpc-stub.sh
      types: [proto]
      language: system
      name: check grpc stub
    - id: gofmt-check
      entry: make
      types: [go]
      args: [check-style]
      language: system
      name: check code style
