const { ccclass, property } = cc._decorator;
/**
 * 游戏自定义事件
 */
@ccclass
export class GameEvent extends cc.Event {
	public static event: cc.EventTarget = new cc.EventTarget(); // 游戏全局自定义事件target

	private _userData: any = null;
	public get userData(): any {
		return this._userData;
	}
	constructor(typeArg: string, data?: any) {
		super(typeArg, null);
		this._userData = data;
	}
}

export enum EventType {
	HTTP_LOGIN_SUCCESS = "GAME_EVENT.HTTP_LOGIN_SUCCESS", //http登录成功

	HTTP_TEST_SUCCESS = "GAME_EVENT.HTTP_TEST_SUCCESS", //httptest
	HTTP_TEST_FAIL = "GAME_EVENT.HTTP_TEST_FAIL", //httptest

	SOCKET_CONNECTED = "GAME_EVENT.SOCKET_CONNECTED",
	SOCKET_ON_CLOSED = "GAME_EVENT.SOCKET_ON_CLOSED",
	SOCKET_ON_ERROR = "GAME_EVENT.SOCKET_ON_ERROR",

	HTTP_STORE_PROFESSION_LIST = "HTTP_STORE_PROFESSION_LIST",

	HTTP_HAS_STORE_PROFESSION_LIST = "HTTP_HAS_STORE_PROFESSION_LIST",

	HTTP_BUY_PROFESSION = "HTTP_BUY_PROFESSION",

	HTTP_GET_NOTICE = "HTTP_GET_NOTICE",

	HTTP_GET_TASK = "HTTP_GET_TASK",

	HTTP_GET_TASK_AWARD = "HTTP_GET_TASK_AWARD",

	HTTP_GET_GAME_RATIO = "HTTP_GET_GAME_RATIO",

	HTTP_GET_GAME_HISTORY = "HTTP_GET_GAME_HISTORY",

	HTTP_GET_GAME_RESULT_PAGE = "HTTP_GET_GAME_RESULT_PAGE",

	HTTP_GET_IS_SUMMARY = "HTTP_GET_IS_SUMMARY",

	HTTP_GET_WEATH_RESULT = "HTTP_GET_WEATH_RESULT",

	HTTP_GET_USERINFO = "HTTP_GET_USERINFO",

	HALL_GET_TASK_MSG = "HALL_GET_TASK_MSG",

	HTTP_GET_SHARE = "HTTP_GET_SHARE",

	HTTP_GET_ASSET_RANK = "HTTP_GET_ASSET_RANK",

	SOCKET_LOGIN_SUCESS = "GAME_EVENT.SOCKET_LOGIN_SUCESS",

	SOCKET_LOGIN_FAIL = "SOCKET_LOGIN_FAIL",

	SOCKET_CHECK_PLAYING = "GAME_EVENT.SOCKET_CHECK_PLAYING",

	SOCKET_CREATE_ROOM = "GAME_EVENT.SOCKET_CREATE_ROOM",

	SOCKET_START_MATCHING = "GAME_EVENT.SOCKET_START_MATCHING",

	SOCKET_START_MATCHING_MSG = "GAME_EVENT.SOCKET_START_MATCHING_MSG",

	SOCKET_MATCHING = "SOCKET_MATCHING",

	SOCKET_MatchMsg = "SOCKET_MatchMsg",

	SOCKET_PREPARE = "SOCKET_PREPARE",

	SOCKET_PrepareMsg = "PrepareMsg",

	SOCKET_GET_ROLES = "SOCKET_GET_ROLES",

	SOCKET_SELECT_ROLE = "SOCKET_SELECT_ROLE",

	SOCKET_SelectRoleMsg = "SOCKET_SelectRoleMsg",

	SOCKET_SYNC_STATE = "SOCKET_SYNC_STATE",

	SOCKET_GET_AVAILABLE_ROOM_SIZE = "SOCKET_GET_AVAILABLE_ROOM_SIZE",

	SOCKET_EXIT_ROOM = "SOCKET_EXIT_ROOM",

	SOCKET_EXIT_MATCH = "SOCKET_EXIT_MATCH",

	SOCKET_AnyoneTimeoutMsg = "SOCKET_AnyoneTimeoutMsg",

	SOCKET_AllReadyMsg = "SOCKET_AllReadyMsg",

	SOCKET_PlayerAllSelectedRoleMsg = "SOCKET_PlayerAllSelectedRoleMsg",

	SOCKET_START_AUCTION = "SOCKET_START_AUCTION",

	SOCKET_GiveUpAuctionMsg = "SOCKET_GiveUpAuctionMsg",

	SOCKET_AuctionBidMsg = "SOCKET_AuctionBidMsg",

	SOCKET_OFFER_AUCTION_BID = "SOCKET_OFFER_AUCTION_BID",

	SOCKET_AuctionResultMsg = "SOCKET_AuctionResultMsg",

	SOCKET_AFK = "SOCKET_AFK",

	//game
	SOCKET_LOAN_QUALIFICATION = "SOCKET_LOAN_QUALIFICATION",
	SOCKET_ROLL = "SOCKET_ROLL",
	SOCKET_RollMsg = "SOCKET_RollMsg",
	SOCKET_NextRollMsg = "SOCKET_NextRollMsg",
	SOCKET_UNEMPLOYMENT_ACK = "SOCKET_UNEMPLOYMENT_ACK",
	SOCKET_PASS = "SOCKET_PASS",
	SOCKET_RE_CONNECT = "SOCKET_RE_CONNECT",
	SOCKET_PlayerReconnectMsg = "SOCKET_PlayerReconnectMsg",
	SOCKET_WageHikeMsg = "SOCKET_WageHikeMsg",
	SOCKET_PAY_ACCIDENT_CONSUME = "SOCKET_PAY_ACCIDENT_CONSUME",
	SOCKET_PayAccidentConsumeMsg = "SOCKET_PayAccidentConsumeMsg",
	SOCKET_PlayerQuitGameMsg = "SOCKET_PlayerQuitGameMsg",
	SOCKET_ChooseChanceMsg = "SOCKET_ChooseChanceMsg",
	SOCKET_BuyMsg = "SOCKET_BuyMsg",
	SOCKET_BUY = "SOCKET_BUY",
	SOCKET_SELL_ASSETS = "SOCKET_SELL_ASSETS",
	SOCKET_GET_CAN_SELL_PLAYER_ASSET = "SOCKET_GET_CAN_SELL_PLAYER_ASSET",
	SOCKET_SellAssetsMsg = "SOCKET_SellAssetsMsg",
	SOCKET_TRY_PAY = "SOCKET_TRY_PAY",
	SOCKET_GIVEUP_CHANCE = "SOCKET_GIVEUP_CHANCE",
	SOCKET_GiveUpChanceMsg = "SOCKET_GiveUpChanceMsg",
	SOCKET_CONFIRM_MARKET_CHANGE = "SOCKET_CONFIRM_MARKET_CHANGE",
	SOCKET_PlayerOutMsg = "SOCKET_PlayerOutMsg",
	SOCKET_CONFIRM_BANKRUPT = "SOCKET_CONFIRM_BANKRUPT",
	SOCKET_GameOverMsg = "SOCKET_GameOverMsg",
	SOCKET_QUIT = "SOCKET_QUIT",
	SOCKET_LOAN_ASSET = "SOCKET_LOAN_ASSET",
	SOCKET_LOAN = "SOCKET_LOAN",
	SOCKET_REPAY_LOAN = "SOCKET_REPAY_LOAN",
	SOCKET_GET_FINANCIAL_REPORTS = "SOCKET_GET_FINANCIAL_REPORTS",
	SOCKET_LoanMsg = "SOCKET_LoanMsg",
	SOCKET_StartAuctionMsg = "SOCKET_StartAuctionMsg",
	SOCKET_GIVEUP_AUCTION = "SOCKET_GIVEUP_AUCTION",
	SOCKET_PlayerAFKMsg = "SOCKET_PlayerAFKMsg",
	SOCKET_GET_AVAILABLE_MAPS = "SOCKET_GET_AVAILABLE_MAPS",
	SOCKET_UPDATE_ROOM_OPTION = "SOCKET_UPDATE_ROOM_OPTION",

	//自定义
	GAME_DICE_END = "GAME_DICE_END",
	GAME_ROAD_MOVE_END = "GAME_ROAD_MOVE_END",
	GAME_SHOW_PAY_CONFIRM = "GAME_SHOW_PAY_CONFIRM",
	GAME_PROMOTE_END = "GAME_PROMOTE_END",
	GAME_BABY_CONFIRM = "GAME_BABY_CONFIRM",
	GAME_CHANCE_BUY = "GAME_CHANCE_BUY",
	GAME_SHOW_BUY_NET = "GAME_SHOW_BUY_NET",
	GAME_SELL_MSG = "GAME_SELL_MSG",
	GAME_CANCEL_SELL="GAME_CANCEL_SELL",
	GAME_SHOW_ACCIDENT_PAY_CONFIRM = "GAME_SHOW_ACCIDENT_PAY_CONFIRM",
	GAME_PAY_COUNT = "GAME_PAY_COUNT",
	GAME_CHANCE_AUCT = "GAME_CHANCE_AUCT",
	GAME_CHANCE_AUCT_OFFER = "GAME_CHANCE_AUCT_OFFER",
	GAME_CHANCE_DETAIL = "GAME_CHANCE_DETAIL",

	SHARE_SUCESS = "SHARE_SUCESS",
	ON_SHOW = "ON_SHOW",
	ON_HIDE = "ON_HIDE"
}
