// Code generated by protoc-gen-go. DO NOT EDIT.
// source: events/general.proto

package events

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GeneralEventType_Enum int32

const (
	GeneralEventType_UNKNOWN GeneralEventType_Enum = 0
	// 用户连接长连接服务并认证成功
	GeneralEventType_USER_ONLINE GeneralEventType_Enum = 1
)

var GeneralEventType_Enum_name = map[int32]string{
	0: "UNKNOWN",
	1: "USER_ONLINE",
}

var GeneralEventType_Enum_value = map[string]int32{
	"UNKNOWN":     0,
	"USER_ONLINE": 1,
}

func (x GeneralEventType_Enum) String() string {
	return proto.EnumName(GeneralEventType_Enum_name, int32(x))
}

func (GeneralEventType_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8a447d5e5beac80f, []int{0, 0}
}

// 事件类型，每种事件有对应的 Message，
// 命名统一为 $(EventName)Event
type GeneralEventType struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneralEventType) Reset()         { *m = GeneralEventType{} }
func (m *GeneralEventType) String() string { return proto.CompactTextString(m) }
func (*GeneralEventType) ProtoMessage()    {}
func (*GeneralEventType) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a447d5e5beac80f, []int{0}
}

func (m *GeneralEventType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralEventType.Unmarshal(m, b)
}
func (m *GeneralEventType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralEventType.Marshal(b, m, deterministic)
}
func (m *GeneralEventType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralEventType.Merge(m, src)
}
func (m *GeneralEventType) XXX_Size() int {
	return xxx_messageInfo_GeneralEventType.Size(m)
}
func (m *GeneralEventType) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralEventType.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralEventType proto.InternalMessageInfo

// 用户连接长连接服务并认证成功
// USER_ONLINE = 1;
type UserOnlineEvent struct {
	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	// 登录时的客户端地址
	ClientAddr string `protobuf:"bytes,2,opt,name=clientAddr,proto3" json:"clientAddr,omitempty"`
	// 登录时的客户端端口
	ClientPort uint32 `protobuf:"varint,3,opt,name=clientPort,proto3" json:"clientPort,omitempty"`
	// 本次登录的 id，每次登录会给 conn 分配一个 id
	// 这个主要是用来给 agent 实现互踢逻辑使用的
	LoginId              string   `protobuf:"bytes,4,opt,name=loginId,proto3" json:"loginId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserOnlineEvent) Reset()         { *m = UserOnlineEvent{} }
func (m *UserOnlineEvent) String() string { return proto.CompactTextString(m) }
func (*UserOnlineEvent) ProtoMessage()    {}
func (*UserOnlineEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a447d5e5beac80f, []int{1}
}

func (m *UserOnlineEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserOnlineEvent.Unmarshal(m, b)
}
func (m *UserOnlineEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserOnlineEvent.Marshal(b, m, deterministic)
}
func (m *UserOnlineEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserOnlineEvent.Merge(m, src)
}
func (m *UserOnlineEvent) XXX_Size() int {
	return xxx_messageInfo_UserOnlineEvent.Size(m)
}
func (m *UserOnlineEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_UserOnlineEvent.DiscardUnknown(m)
}

var xxx_messageInfo_UserOnlineEvent proto.InternalMessageInfo

func (m *UserOnlineEvent) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserOnlineEvent) GetClientAddr() string {
	if m != nil {
		return m.ClientAddr
	}
	return ""
}

func (m *UserOnlineEvent) GetClientPort() uint32 {
	if m != nil {
		return m.ClientPort
	}
	return 0
}

func (m *UserOnlineEvent) GetLoginId() string {
	if m != nil {
		return m.LoginId
	}
	return ""
}

type GeneralEvent struct {
	Type GeneralEventType_Enum `protobuf:"varint,1,opt,name=type,proto3,enum=pb.events.GeneralEventType_Enum" json:"type,omitempty"`
	// 事件发生的时间戳
	Timestamp *timestamp.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 根据内容不同的消息
	Content              *any.Any `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneralEvent) Reset()         { *m = GeneralEvent{} }
func (m *GeneralEvent) String() string { return proto.CompactTextString(m) }
func (*GeneralEvent) ProtoMessage()    {}
func (*GeneralEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a447d5e5beac80f, []int{2}
}

func (m *GeneralEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralEvent.Unmarshal(m, b)
}
func (m *GeneralEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralEvent.Marshal(b, m, deterministic)
}
func (m *GeneralEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralEvent.Merge(m, src)
}
func (m *GeneralEvent) XXX_Size() int {
	return xxx_messageInfo_GeneralEvent.Size(m)
}
func (m *GeneralEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralEvent.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralEvent proto.InternalMessageInfo

func (m *GeneralEvent) GetType() GeneralEventType_Enum {
	if m != nil {
		return m.Type
	}
	return GeneralEventType_UNKNOWN
}

func (m *GeneralEvent) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *GeneralEvent) GetContent() *any.Any {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.events.GeneralEventType_Enum", GeneralEventType_Enum_name, GeneralEventType_Enum_value)
	proto.RegisterType((*GeneralEventType)(nil), "pb.events.GeneralEventType")
	proto.RegisterType((*UserOnlineEvent)(nil), "pb.events.UserOnlineEvent")
	proto.RegisterType((*GeneralEvent)(nil), "pb.events.GeneralEvent")
}

func init() { proto.RegisterFile("events/general.proto", fileDescriptor_8a447d5e5beac80f) }

var fileDescriptor_8a447d5e5beac80f = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x8d, 0xad, 0x2d, 0x9d, 0xaa, 0x2d, 0x4b, 0x91, 0xd8, 0x83, 0x86, 0x20, 0x92, 0x8b,
	0x1b, 0xa8, 0x1e, 0x7a, 0xad, 0x10, 0xa4, 0x28, 0xa9, 0xc4, 0x16, 0xc1, 0x8b, 0xe4, 0xcf, 0x18,
	0x02, 0xc9, 0x6e, 0xd8, 0x6c, 0x0a, 0x39, 0xfb, 0x7d, 0xfc, 0x8c, 0xd2, 0x8d, 0x69, 0x4b, 0x3d,
	0xce, 0xbc, 0xdf, 0x1b, 0xe6, 0x3d, 0x18, 0xe1, 0x1a, 0x99, 0x2c, 0xec, 0x18, 0x19, 0x0a, 0x3f,
	0xa5, 0xb9, 0xe0, 0x92, 0x93, 0x5e, 0x1e, 0xd0, 0x5a, 0x18, 0x5f, 0xc7, 0x9c, 0xc7, 0x29, 0xda,
	0x4a, 0x08, 0xca, 0x2f, 0x5b, 0x26, 0x19, 0x16, 0xd2, 0xcf, 0xf2, 0x9a, 0x1d, 0x5f, 0x1e, 0x02,
	0x3e, 0xab, 0x6a, 0xc9, 0x9c, 0xc2, 0xf0, 0xa9, 0xbe, 0xeb, 0x6c, 0x8e, 0x2d, 0xab, 0x1c, 0xcd,
	0x1b, 0x68, 0x3b, 0xac, 0xcc, 0x48, 0x1f, 0xba, 0x2b, 0xf7, 0xd9, 0x5d, 0xbc, 0xbb, 0xc3, 0x23,
	0x32, 0x80, 0xfe, 0xea, 0xcd, 0xf1, 0x3e, 0x17, 0xee, 0xcb, 0xdc, 0x75, 0x86, 0x9a, 0xf9, 0xad,
	0xc1, 0x60, 0x55, 0xa0, 0x58, 0xb0, 0x34, 0x61, 0xa8, 0xdc, 0xe4, 0x02, 0x3a, 0x65, 0x81, 0x62,
	0x1e, 0xe9, 0x9a, 0xa1, 0x59, 0x2d, 0xef, 0x6f, 0x22, 0x57, 0x00, 0x61, 0x9a, 0x20, 0x93, 0xb3,
	0x28, 0x12, 0xfa, 0xb1, 0xa1, 0x59, 0x3d, 0x6f, 0x6f, 0xb3, 0xd3, 0x5f, 0xb9, 0x90, 0x7a, 0xcb,
	0xd0, 0xac, 0x33, 0x6f, 0x6f, 0x43, 0x74, 0xe8, 0xa6, 0x3c, 0x4e, 0xd8, 0x3c, 0xd2, 0xdb, 0xca,
	0xdc, 0x8c, 0xe6, 0x8f, 0x06, 0xa7, 0xfb, 0x01, 0xc8, 0x03, 0xb4, 0x65, 0x95, 0xa3, 0x7a, 0xe0,
	0x7c, 0x62, 0xd0, 0x6d, 0x4d, 0xf4, 0x30, 0x27, 0xdd, 0x84, 0xf4, 0x14, 0x4d, 0xa6, 0xd0, 0xdb,
	0x96, 0xa6, 0xfe, 0xeb, 0x4f, 0xc6, 0xb4, 0x6e, 0x8d, 0x36, 0xad, 0xd1, 0x65, 0x43, 0x78, 0x3b,
	0x98, 0x50, 0xe8, 0x86, 0x9c, 0x49, 0x64, 0x52, 0x3f, 0x51, 0xbe, 0xd1, 0x3f, 0xdf, 0x8c, 0x55,
	0x5e, 0x03, 0x3d, 0x5a, 0x1f, 0xb7, 0x71, 0x22, 0x53, 0x3f, 0xa0, 0x21, 0xcf, 0xec, 0x35, 0x86,
	0x92, 0x8b, 0x32, 0xb7, 0xfd, 0xa2, 0x40, 0x79, 0x97, 0x07, 0x76, 0xcc, 0xed, 0xfa, 0xdf, 0xa0,
	0xa3, 0x0e, 0xdc, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x60, 0x24, 0x12, 0xcf, 0x00, 0x02, 0x00,
	0x00,
}
