// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/backend.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Stack                string   `protobuf:"bytes,3,opt,name=stack,proto3" json:"stack,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_df94a068cb76f6c1, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetStack() string {
	if m != nil {
		return m.Stack
	}
	return ""
}

type StreamInitParam struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamInitParam) Reset()         { *m = StreamInitParam{} }
func (m *StreamInitParam) String() string { return proto.CompactTextString(m) }
func (*StreamInitParam) ProtoMessage()    {}
func (*StreamInitParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_df94a068cb76f6c1, []int{1}
}

func (m *StreamInitParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamInitParam.Unmarshal(m, b)
}
func (m *StreamInitParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamInitParam.Marshal(b, m, deterministic)
}
func (m *StreamInitParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamInitParam.Merge(m, src)
}
func (m *StreamInitParam) XXX_Size() int {
	return xxx_messageInfo_StreamInitParam.Size(m)
}
func (m *StreamInitParam) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamInitParam.DiscardUnknown(m)
}

var xxx_messageInfo_StreamInitParam proto.InternalMessageInfo

func (m *StreamInitParam) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func init() {
	proto.RegisterType((*Error)(nil), "pb.common.Error")
	proto.RegisterType((*StreamInitParam)(nil), "pb.common.StreamInitParam")
}

func init() { proto.RegisterFile("common/backend.proto", fileDescriptor_df94a068cb76f6c1) }

var fileDescriptor_df94a068cb76f6c1 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0x41, 0x6b, 0x84, 0x30,
	0x10, 0x85, 0xb1, 0x56, 0x8b, 0xb9, 0x14, 0x82, 0x94, 0x1c, 0xc5, 0x43, 0xb1, 0x87, 0x9a, 0x43,
	0xff, 0x41, 0xa1, 0x07, 0xe9, 0x65, 0x71, 0x6f, 0x7b, 0x9b, 0xc4, 0x41, 0xc4, 0x8d, 0x13, 0x26,
	0x71, 0x7f, 0xff, 0x42, 0xdc, 0xbd, 0xbd, 0xef, 0x3d, 0x78, 0x7c, 0xa2, 0xb6, 0xe4, 0x1c, 0x6d,
	0xda, 0x80, 0x5d, 0x71, 0x9b, 0x7a, 0xcf, 0x14, 0x49, 0x56, 0xde, 0xf4, 0xc7, 0xd0, 0xfe, 0x8b,
	0xe2, 0x8f, 0x99, 0x58, 0x4a, 0xf1, 0x6a, 0x69, 0x42, 0x95, 0x35, 0x59, 0x57, 0x8c, 0x29, 0x4b,
	0x25, 0xde, 0x1c, 0x86, 0x00, 0x33, 0xaa, 0x97, 0x26, 0xeb, 0xaa, 0xf1, 0x89, 0xb2, 0x16, 0x45,
	0x88, 0x60, 0x57, 0x95, 0xa7, 0xfe, 0x80, 0xf6, 0x4b, 0xbc, 0x9f, 0x23, 0x23, 0xb8, 0x61, 0x5b,
	0xe2, 0x09, 0x18, 0x9c, 0xfc, 0x10, 0xe5, 0x1e, 0x90, 0x87, 0x29, 0x1d, 0xe7, 0xe3, 0x83, 0x7e,
	0xbb, 0xcb, 0xe7, 0xbc, 0xc4, 0x2b, 0x24, 0x11, 0x7d, 0x43, 0x1b, 0x89, 0x77, 0xaf, 0x21, 0x04,
	0x8c, 0xdf, 0xde, 0xe8, 0x99, 0xf4, 0x61, 0x68, 0xca, 0xe4, 0xfc, 0x73, 0x0f, 0x00, 0x00, 0xff,
	0xff, 0x1d, 0x95, 0x04, 0x98, 0xcb, 0x00, 0x00, 0x00,
}
