// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/main.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 系统间消息传输格式
// client ==>[content + mars.CmdID]===> agent ==>[Payload]===> backendSrv。 客户端同步请求通过Payload进行转化
// backendSrv ==>[Payload]===> agent ===>[mars.CMD_PUSH + Payload]===> client。 Push过程通过Payload进行转化
type Payload struct {
	// 消息类型，对应CmdID
	Type int32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	// 用户ID
	// 如果是客户端的请求: 请求用户ID
	// 如果是服务端响应客户端的请求： 对应请求的用户ID
	// 如果是服务端push消息到客户端： 该push消息内容的主语（需要按业务确定）  // TODO 值得商榷，userId是content的主语，影响逻辑分层
	UserId int64 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	// 业务数据，任意格式，当前是proto的序列化格式
	Content []byte `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// 推送时用来标注推送用户 id 的字段
	// 原来的 agent -> lobby, agent -> game 是每个用户单独建立一条推送通道（gRPC stream），不过这样做不方便
	// 推送通道的维护
	// 现在修改成 agent 跟 lobby 和每个 game 只建立一个推送通道，不过这样就需要标识推送过去的消息是推给谁的
	// 这个字段就是拿来做这个用处的
	PushToUserId         int64    `protobuf:"varint,4,opt,name=pushToUserId,proto3" json:"pushToUserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_41e6ffcad7eb93ee, []int{0}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Payload) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Payload) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Payload) GetPushToUserId() int64 {
	if m != nil {
		return m.PushToUserId
	}
	return 0
}

type Timer struct {
	Total                int32    `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Remaining            int32    `protobuf:"varint,2,opt,name=remaining,proto3" json:"remaining,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timer) Reset()         { *m = Timer{} }
func (m *Timer) String() string { return proto.CompactTextString(m) }
func (*Timer) ProtoMessage()    {}
func (*Timer) Descriptor() ([]byte, []int) {
	return fileDescriptor_41e6ffcad7eb93ee, []int{1}
}

func (m *Timer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timer.Unmarshal(m, b)
}
func (m *Timer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timer.Marshal(b, m, deterministic)
}
func (m *Timer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timer.Merge(m, src)
}
func (m *Timer) XXX_Size() int {
	return xxx_messageInfo_Timer.Size(m)
}
func (m *Timer) XXX_DiscardUnknown() {
	xxx_messageInfo_Timer.DiscardUnknown(m)
}

var xxx_messageInfo_Timer proto.InternalMessageInfo

func (m *Timer) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Timer) GetRemaining() int32 {
	if m != nil {
		return m.Remaining
	}
	return 0
}

func init() {
	proto.RegisterType((*Payload)(nil), "pb.common.Payload")
	proto.RegisterType((*Timer)(nil), "pb.common.timer")
}

func init() { proto.RegisterFile("common/main.proto", fileDescriptor_41e6ffcad7eb93ee) }

var fileDescriptor_41e6ffcad7eb93ee = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x31, 0x4b, 0x04, 0x31,
	0x10, 0x85, 0x59, 0xef, 0x72, 0xc7, 0x0d, 0xd7, 0x38, 0x88, 0x6c, 0x61, 0xb1, 0x6c, 0x21, 0x69,
	0xbc, 0x14, 0x96, 0x76, 0x76, 0x76, 0x12, 0xb4, 0xb1, 0xcb, 0xee, 0x85, 0x35, 0xb0, 0xc9, 0x84,
	0x64, 0x56, 0xd8, 0x7f, 0x2f, 0x26, 0x8a, 0x5c, 0x37, 0xef, 0x83, 0x37, 0x33, 0x1f, 0x5c, 0x8f,
	0xe4, 0x3d, 0x05, 0xe5, 0x8d, 0x0b, 0xa7, 0x98, 0x88, 0x09, 0x0f, 0x71, 0x38, 0x55, 0xda, 0x67,
	0xd8, 0xbf, 0x9a, 0x75, 0x26, 0x73, 0x46, 0x84, 0x2d, 0xaf, 0xd1, 0xb6, 0x4d, 0xd7, 0x48, 0xa1,
	0xcb, 0x8c, 0xb7, 0xb0, 0x5b, 0xb2, 0x4d, 0x2f, 0xe7, 0xf6, 0xaa, 0x6b, 0xe4, 0x46, 0xff, 0x26,
	0x6c, 0x61, 0x3f, 0x52, 0x60, 0x1b, 0xb8, 0xdd, 0x74, 0x8d, 0x3c, 0xea, 0xbf, 0x88, 0x3d, 0x1c,
	0xe3, 0x92, 0x3f, 0xdf, 0xe8, 0xbd, 0xf6, 0xb6, 0xa5, 0x77, 0xc1, 0xfa, 0x27, 0x10, 0xec, 0xbc,
	0x4d, 0x78, 0x03, 0x82, 0x89, 0xcd, 0x5c, 0x96, 0x08, 0x5d, 0x03, 0xde, 0xc1, 0x21, 0xd9, 0x9f,
	0x77, 0x5d, 0x98, 0xca, 0x5d, 0xa1, 0xff, 0xc1, 0xb3, 0xfc, 0xb8, 0x9f, 0x1c, 0xcf, 0xa6, 0x28,
	0xa8, 0x2f, 0x3b, 0x32, 0xa5, 0x25, 0x2a, 0x93, 0xb3, 0xe5, 0x87, 0x38, 0xa8, 0x89, 0x54, 0x75,
	0x1b, 0x76, 0xc5, 0xf6, 0xf1, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x20, 0x8c, 0x5a, 0x6e, 0x02, 0x01,
	0x00, 0x00,
}
