// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/state.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 现金流
type CashFlow struct {
	MonthlySalary         int64    `protobuf:"varint,1,opt,name=monthlySalary,proto3" json:"monthlySalary,omitempty"`
	MonthlyIncomeExSalary int64    `protobuf:"varint,2,opt,name=monthlyIncomeExSalary,proto3" json:"monthlyIncomeExSalary,omitempty"`
	MonthlyExpenses       int64    `protobuf:"varint,3,opt,name=monthlyExpenses,proto3" json:"monthlyExpenses,omitempty"`
	MonthlyCashFlow       int64    `protobuf:"varint,4,opt,name=monthlyCashFlow,proto3" json:"monthlyCashFlow,omitempty"`
	TotalCash             int64    `protobuf:"varint,5,opt,name=totalCash,proto3" json:"totalCash,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *CashFlow) Reset()         { *m = CashFlow{} }
func (m *CashFlow) String() string { return proto.CompactTextString(m) }
func (*CashFlow) ProtoMessage()    {}
func (*CashFlow) Descriptor() ([]byte, []int) {
	return fileDescriptor_b87151e42d73a9b3, []int{0}
}

func (m *CashFlow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CashFlow.Unmarshal(m, b)
}
func (m *CashFlow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CashFlow.Marshal(b, m, deterministic)
}
func (m *CashFlow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CashFlow.Merge(m, src)
}
func (m *CashFlow) XXX_Size() int {
	return xxx_messageInfo_CashFlow.Size(m)
}
func (m *CashFlow) XXX_DiscardUnknown() {
	xxx_messageInfo_CashFlow.DiscardUnknown(m)
}

var xxx_messageInfo_CashFlow proto.InternalMessageInfo

func (m *CashFlow) GetMonthlySalary() int64 {
	if m != nil {
		return m.MonthlySalary
	}
	return 0
}

func (m *CashFlow) GetMonthlyIncomeExSalary() int64 {
	if m != nil {
		return m.MonthlyIncomeExSalary
	}
	return 0
}

func (m *CashFlow) GetMonthlyExpenses() int64 {
	if m != nil {
		return m.MonthlyExpenses
	}
	return 0
}

func (m *CashFlow) GetMonthlyCashFlow() int64 {
	if m != nil {
		return m.MonthlyCashFlow
	}
	return 0
}

func (m *CashFlow) GetTotalCash() int64 {
	if m != nil {
		return m.TotalCash
	}
	return 0
}

// 资产（负债也作为一种资产)
type Asset struct {
	AssetId              int64    `protobuf:"varint,1,opt,name=assetId,proto3" json:"assetId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 int32    `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	TotalPrice           int64    `protobuf:"varint,4,opt,name=totalPrice,proto3" json:"totalPrice,omitempty"`
	Liabilities          int64    `protobuf:"varint,5,opt,name=Liabilities,proto3" json:"Liabilities,omitempty"`
	MonthlyCashFlow      int64    `protobuf:"varint,6,opt,name=monthlyCashFlow,proto3" json:"monthlyCashFlow,omitempty"`
	Quantity             int32    `protobuf:"varint,8,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Shard                int32    `protobuf:"varint,9,opt,name=shard,proto3" json:"shard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Asset) Reset()         { *m = Asset{} }
func (m *Asset) String() string { return proto.CompactTextString(m) }
func (*Asset) ProtoMessage()    {}
func (*Asset) Descriptor() ([]byte, []int) {
	return fileDescriptor_b87151e42d73a9b3, []int{1}
}

func (m *Asset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Asset.Unmarshal(m, b)
}
func (m *Asset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Asset.Marshal(b, m, deterministic)
}
func (m *Asset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Asset.Merge(m, src)
}
func (m *Asset) XXX_Size() int {
	return xxx_messageInfo_Asset.Size(m)
}
func (m *Asset) XXX_DiscardUnknown() {
	xxx_messageInfo_Asset.DiscardUnknown(m)
}

var xxx_messageInfo_Asset proto.InternalMessageInfo

func (m *Asset) GetAssetId() int64 {
	if m != nil {
		return m.AssetId
	}
	return 0
}

func (m *Asset) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Asset) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Asset) GetTotalPrice() int64 {
	if m != nil {
		return m.TotalPrice
	}
	return 0
}

func (m *Asset) GetLiabilities() int64 {
	if m != nil {
		return m.Liabilities
	}
	return 0
}

func (m *Asset) GetMonthlyCashFlow() int64 {
	if m != nil {
		return m.MonthlyCashFlow
	}
	return 0
}

func (m *Asset) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Asset) GetShard() int32 {
	if m != nil {
		return m.Shard
	}
	return 0
}

type PlayerRecord struct {
	UserId          int64     `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CashFlow        *CashFlow `protobuf:"bytes,2,opt,name=cashFlow,proto3" json:"cashFlow,omitempty"`
	BehaviorType    int32     `protobuf:"varint,3,opt,name=BehaviorType,proto3" json:"BehaviorType,omitempty"`
	Degree          float32   `protobuf:"fixed32,5,opt,name=degree,proto3" json:"degree,omitempty"`
	IsOut           bool      `protobuf:"varint,6,opt,name=isOut,proto3" json:"isOut,omitempty"`
	VideotapeId     int64     `protobuf:"varint,7,opt,name=videotapeId,proto3" json:"videotapeId,omitempty"`
	CurrentLocation int32     `protobuf:"varint,8,opt,name=currentLocation,proto3" json:"currentLocation,omitempty"`
	Cycle           int32     `protobuf:"varint,9,opt,name=cycle,proto3" json:"cycle,omitempty"`
	// 玩家年龄, 默认25, 如果有填写生日使用生日计算, 每经过一次结算日 +1
	Age int32 `protobuf:"varint,10,opt,name=age,proto3" json:"age,omitempty"`
	// 初始年龄, 根据玩家填写的生日计算初始年龄
	InitAge              int32    `protobuf:"varint,11,opt,name=initAge,proto3" json:"initAge,omitempty"` // Deprecated: Do not use.
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerRecord) Reset()         { *m = PlayerRecord{} }
func (m *PlayerRecord) String() string { return proto.CompactTextString(m) }
func (*PlayerRecord) ProtoMessage()    {}
func (*PlayerRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_b87151e42d73a9b3, []int{2}
}

func (m *PlayerRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerRecord.Unmarshal(m, b)
}
func (m *PlayerRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerRecord.Marshal(b, m, deterministic)
}
func (m *PlayerRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerRecord.Merge(m, src)
}
func (m *PlayerRecord) XXX_Size() int {
	return xxx_messageInfo_PlayerRecord.Size(m)
}
func (m *PlayerRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerRecord.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerRecord proto.InternalMessageInfo

func (m *PlayerRecord) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PlayerRecord) GetCashFlow() *CashFlow {
	if m != nil {
		return m.CashFlow
	}
	return nil
}

func (m *PlayerRecord) GetBehaviorType() int32 {
	if m != nil {
		return m.BehaviorType
	}
	return 0
}

func (m *PlayerRecord) GetDegree() float32 {
	if m != nil {
		return m.Degree
	}
	return 0
}

func (m *PlayerRecord) GetIsOut() bool {
	if m != nil {
		return m.IsOut
	}
	return false
}

func (m *PlayerRecord) GetVideotapeId() int64 {
	if m != nil {
		return m.VideotapeId
	}
	return 0
}

func (m *PlayerRecord) GetCurrentLocation() int32 {
	if m != nil {
		return m.CurrentLocation
	}
	return 0
}

func (m *PlayerRecord) GetCycle() int32 {
	if m != nil {
		return m.Cycle
	}
	return 0
}

func (m *PlayerRecord) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

// Deprecated: Do not use.
func (m *PlayerRecord) GetInitAge() int32 {
	if m != nil {
		return m.InitAge
	}
	return 0
}

type GameState struct {
	UserId               int64           `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	RoundSeq             int32           `protobuf:"varint,3,opt,name=roundSeq,proto3" json:"roundSeq,omitempty"`
	CurrentLocation      int32           `protobuf:"varint,4,opt,name=currentLocation,proto3" json:"currentLocation,omitempty"`
	DiceNum              int32           `protobuf:"varint,5,opt,name=diceNum,proto3" json:"diceNum,omitempty"`
	RoundData            *RoundData      `protobuf:"bytes,6,opt,name=roundData,proto3" json:"roundData,omitempty"`
	Scenario             *Scenario       `protobuf:"bytes,7,opt,name=scenario,proto3" json:"scenario,omitempty"`
	PlayerRecords        []*PlayerRecord `protobuf:"bytes,8,rep,name=playerRecords,proto3" json:"playerRecords,omitempty"`
	Timer                *Timer          `protobuf:"bytes,9,opt,name=timer,proto3" json:"timer,omitempty"`
	GlobalTimer          *Timer          `protobuf:"bytes,10,opt,name=globalTimer,proto3" json:"globalTimer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GameState) Reset()         { *m = GameState{} }
func (m *GameState) String() string { return proto.CompactTextString(m) }
func (*GameState) ProtoMessage()    {}
func (*GameState) Descriptor() ([]byte, []int) {
	return fileDescriptor_b87151e42d73a9b3, []int{3}
}

func (m *GameState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameState.Unmarshal(m, b)
}
func (m *GameState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameState.Marshal(b, m, deterministic)
}
func (m *GameState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameState.Merge(m, src)
}
func (m *GameState) XXX_Size() int {
	return xxx_messageInfo_GameState.Size(m)
}
func (m *GameState) XXX_DiscardUnknown() {
	xxx_messageInfo_GameState.DiscardUnknown(m)
}

var xxx_messageInfo_GameState proto.InternalMessageInfo

func (m *GameState) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GameState) GetRoundSeq() int32 {
	if m != nil {
		return m.RoundSeq
	}
	return 0
}

func (m *GameState) GetCurrentLocation() int32 {
	if m != nil {
		return m.CurrentLocation
	}
	return 0
}

func (m *GameState) GetDiceNum() int32 {
	if m != nil {
		return m.DiceNum
	}
	return 0
}

func (m *GameState) GetRoundData() *RoundData {
	if m != nil {
		return m.RoundData
	}
	return nil
}

func (m *GameState) GetScenario() *Scenario {
	if m != nil {
		return m.Scenario
	}
	return nil
}

func (m *GameState) GetPlayerRecords() []*PlayerRecord {
	if m != nil {
		return m.PlayerRecords
	}
	return nil
}

func (m *GameState) GetTimer() *Timer {
	if m != nil {
		return m.Timer
	}
	return nil
}

func (m *GameState) GetGlobalTimer() *Timer {
	if m != nil {
		return m.GlobalTimer
	}
	return nil
}

type PlayerRole struct {
	// 角色 ID
	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// 角色名称
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	// 用户 id
	UserId int64 `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	// 职业头像
	Avatar string `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	// 职业的 flag, 是职业的唯一标志
	Flag                 string   `protobuf:"bytes,5,opt,name=flag,proto3" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerRole) Reset()         { *m = PlayerRole{} }
func (m *PlayerRole) String() string { return proto.CompactTextString(m) }
func (*PlayerRole) ProtoMessage()    {}
func (*PlayerRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_b87151e42d73a9b3, []int{4}
}

func (m *PlayerRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerRole.Unmarshal(m, b)
}
func (m *PlayerRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerRole.Marshal(b, m, deterministic)
}
func (m *PlayerRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerRole.Merge(m, src)
}
func (m *PlayerRole) XXX_Size() int {
	return xxx_messageInfo_PlayerRole.Size(m)
}
func (m *PlayerRole) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerRole.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerRole proto.InternalMessageInfo

func (m *PlayerRole) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *PlayerRole) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlayerRole) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PlayerRole) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *PlayerRole) GetFlag() string {
	if m != nil {
		return m.Flag
	}
	return ""
}

func init() {
	proto.RegisterType((*CashFlow)(nil), "pb.common.CashFlow")
	proto.RegisterType((*Asset)(nil), "pb.common.Asset")
	proto.RegisterType((*PlayerRecord)(nil), "pb.common.PlayerRecord")
	proto.RegisterType((*GameState)(nil), "pb.common.GameState")
	proto.RegisterType((*PlayerRole)(nil), "pb.common.PlayerRole")
}

func init() { proto.RegisterFile("common/state.proto", fileDescriptor_b87151e42d73a9b3) }

var fileDescriptor_b87151e42d73a9b3 = []byte{
	// 666 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0xcb, 0x6e, 0xdb, 0x3a,
	0x10, 0x85, 0xed, 0xf8, 0xa1, 0x71, 0x72, 0x6f, 0x2e, 0x6f, 0x1e, 0x82, 0x11, 0x14, 0x81, 0x51,
	0x04, 0xde, 0xd4, 0x06, 0xdc, 0x6e, 0xbb, 0x48, 0x9a, 0xb4, 0x30, 0x10, 0xa4, 0x01, 0x9d, 0x55,
	0x37, 0x05, 0x2d, 0x4d, 0x6d, 0x02, 0x92, 0xa8, 0x50, 0xb4, 0x1b, 0xaf, 0xfb, 0x59, 0xfd, 0x91,
	0xfe, 0x41, 0x7f, 0xa3, 0xe0, 0x88, 0x52, 0xa4, 0xc0, 0xdd, 0xcd, 0x9c, 0x39, 0x22, 0xcf, 0x9c,
	0xe1, 0x08, 0x58, 0xa0, 0xe2, 0x58, 0x25, 0x93, 0xcc, 0x08, 0x83, 0xe3, 0x54, 0x2b, 0xa3, 0x98,
	0x97, 0x2e, 0xc6, 0x39, 0x3c, 0x38, 0x2e, 0xca, 0x01, 0x26, 0x42, 0x4b, 0x95, 0x33, 0x06, 0xa7,
	0x0e, 0xd6, 0x6a, 0x9d, 0x84, 0x5f, 0x43, 0x61, 0x84, 0x2b, 0xfc, 0xe7, 0x0a, 0xb1, 0x90, 0x49,
	0x0e, 0x0d, 0x7f, 0x35, 0xa0, 0xf7, 0x41, 0x64, 0xab, 0x8f, 0x91, 0xfa, 0xce, 0x5e, 0xc3, 0x41,
	0xac, 0x12, 0xb3, 0x8a, 0xb6, 0x73, 0x11, 0x09, 0xbd, 0xf5, 0x1b, 0xe7, 0x8d, 0x51, 0x8b, 0xd7,
	0x41, 0xf6, 0x0e, 0x8e, 0x1d, 0x30, 0x4b, 0x02, 0x15, 0xe3, 0xcd, 0x93, 0x63, 0x37, 0x89, 0xbd,
	0xbb, 0xc8, 0x46, 0xf0, 0xaf, 0x2b, 0xdc, 0x3c, 0xa5, 0x98, 0x64, 0x98, 0xf9, 0x2d, 0xe2, 0xbf,
	0x84, 0x2b, 0xcc, 0x42, 0x98, 0xbf, 0x57, 0x63, 0x96, 0x7a, 0xcf, 0xc0, 0x33, 0xca, 0x88, 0xc8,
	0x02, 0x7e, 0x9b, 0x38, 0xcf, 0xc0, 0xf0, 0x77, 0x03, 0xda, 0x97, 0x59, 0x86, 0x86, 0xf9, 0xd0,
	0x15, 0x36, 0x98, 0x85, 0xae, 0xa3, 0x22, 0x65, 0x0c, 0xf6, 0x12, 0x11, 0x23, 0x49, 0xf7, 0x38,
	0xc5, 0x16, 0x33, 0xdb, 0x14, 0x49, 0x5e, 0x9b, 0x53, 0xcc, 0x5e, 0x01, 0xd0, 0xc1, 0xf7, 0x5a,
	0x06, 0xe8, 0xe4, 0x54, 0x10, 0x76, 0x0e, 0xfd, 0x5b, 0x29, 0x16, 0x32, 0x92, 0x46, 0x62, 0xe6,
	0xb4, 0x54, 0xa1, 0x5d, 0x5d, 0x75, 0x76, 0x77, 0x35, 0x80, 0xde, 0xe3, 0x5a, 0x24, 0x46, 0x9a,
	0xad, 0xdf, 0x23, 0x0d, 0x65, 0xce, 0x8e, 0xa0, 0x9d, 0xad, 0x84, 0x0e, 0x7d, 0x8f, 0x0a, 0x79,
	0x32, 0xfc, 0xd9, 0x84, 0xfd, 0xfb, 0x48, 0x6c, 0x51, 0x73, 0x0c, 0x94, 0x0e, 0xd9, 0x09, 0x74,
	0xd6, 0x19, 0xea, 0xb2, 0x5f, 0x97, 0xb1, 0x09, 0xf4, 0x82, 0xe2, 0x76, 0xdb, 0x72, 0x7f, 0xfa,
	0xff, 0xb8, 0x7c, 0x4e, 0xe3, 0x42, 0x01, 0x2f, 0x49, 0x6c, 0x08, 0xfb, 0x57, 0xb8, 0x12, 0x1b,
	0xa9, 0xf4, 0xc3, 0xb3, 0x27, 0x35, 0xcc, 0x5e, 0x16, 0xe2, 0x52, 0x23, 0x52, 0xdb, 0x4d, 0xee,
	0x32, 0xab, 0x55, 0x66, 0x9f, 0xd7, 0x86, 0xfa, 0xec, 0xf1, 0x3c, 0xb1, 0x4e, 0x6d, 0x64, 0x88,
	0xca, 0x88, 0x14, 0x67, 0xa1, 0xdf, 0xcd, 0x9d, 0xaa, 0x40, 0xd6, 0xa9, 0x60, 0xad, 0x35, 0x26,
	0xe6, 0x56, 0x05, 0xc2, 0x48, 0x95, 0x38, 0x1b, 0x5e, 0xc2, 0xf6, 0x86, 0x60, 0x1b, 0x44, 0x58,
	0xb8, 0x41, 0x09, 0x3b, 0x84, 0x96, 0x58, 0xa2, 0x0f, 0x84, 0xd9, 0x90, 0x9d, 0x41, 0x57, 0x26,
	0xd2, 0x5c, 0x2e, 0xd1, 0xef, 0x5b, 0xf4, 0xaa, 0xe9, 0x37, 0x78, 0x01, 0x0d, 0x7f, 0xb4, 0xc0,
	0xfb, 0x24, 0x62, 0x9c, 0xdb, 0x25, 0xab, 0x58, 0xd7, 0xac, 0x59, 0x37, 0x80, 0x1e, 0xed, 0xd3,
	0x1c, 0x1f, 0x9d, 0x0b, 0x65, 0xbe, 0x4b, 0xf1, 0xde, 0x6e, 0xc5, 0x3e, 0x74, 0x43, 0x19, 0xe0,
	0xdd, 0x3a, 0x26, 0xb3, 0xda, 0xbc, 0x48, 0xd9, 0x14, 0x3c, 0x3a, 0xef, 0x5a, 0x18, 0x41, 0x8e,
	0xf5, 0xa7, 0x47, 0x95, 0xd9, 0xf0, 0xa2, 0xc6, 0x9f, 0x69, 0x76, 0x9c, 0xc5, 0xea, 0x93, 0x91,
	0xf5, 0x71, 0xce, 0x5d, 0x89, 0x97, 0x24, 0xf6, 0x1e, 0x0e, 0xd2, 0xca, 0x3b, 0xc9, 0xfc, 0xde,
	0x79, 0x6b, 0xd4, 0x9f, 0x9e, 0x56, 0xbe, 0xaa, 0xbe, 0x23, 0x5e, 0x67, 0xb3, 0x0b, 0x68, 0x1b,
	0x19, 0xa3, 0x26, 0xbf, 0xfb, 0xd3, 0xc3, 0xca, 0x67, 0x84, 0xf3, 0xbc, 0xcc, 0xa6, 0xd0, 0x5f,
	0x46, 0x6a, 0x21, 0xa2, 0x07, 0x62, 0xc3, 0x5f, 0xd8, 0x55, 0xd2, 0xd0, 0x00, 0xb8, 0xab, 0x55,
	0x84, 0xec, 0x1f, 0x68, 0xce, 0xae, 0xdd, 0xe3, 0x6d, 0xce, 0xae, 0xed, 0x4e, 0xde, 0x55, 0xf6,
	0xd4, 0xc6, 0x95, 0x49, 0xb5, 0x6a, 0x93, 0x3a, 0x81, 0x8e, 0xd8, 0x08, 0x23, 0x34, 0x0d, 0xc1,
	0xe3, 0x2e, 0xb3, 0x67, 0x7c, 0x8b, 0xc4, 0x92, 0x8c, 0xf7, 0x38, 0xc5, 0x57, 0xa3, 0x2f, 0x17,
	0x4b, 0x69, 0x22, 0x41, 0xca, 0x26, 0x1b, 0x0c, 0x8c, 0xd2, 0xeb, 0x74, 0x42, 0xbf, 0x87, 0x37,
	0xe9, 0x62, 0xb2, 0x54, 0x93, 0x5c, 0xf2, 0xa2, 0x43, 0xff, 0xcb, 0xb7, 0x7f, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x76, 0xb8, 0xa5, 0xf3, 0x93, 0x05, 0x00, 0x00,
}
