// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/types.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 玩家的状态
type PlayerState int32

const (
	// 开始（未在游戏和房间中就是这个状态）
	PlayerState_PLAYER_STATE_BEGIN PlayerState = 0
	// 在某个房间中
	PlayerState_PLAYER_STATE_IN_ROOM PlayerState = 1
	// 匹配中
	PlayerState_PLAYER_STATE_MATCHING PlayerState = 2
	// 已匹配成功
	PlayerState_PLAYER_STATE_MATCHED PlayerState = 3
	// 已准备就绪
	PlayerState_PLAYER_STATE_READY PlayerState = 4
	// 进行游戏中
	PlayerState_PLAYER_STATE_PLAYING PlayerState = 5
)

var PlayerState_name = map[int32]string{
	0: "PLAYER_STATE_BEGIN",
	1: "PLAYER_STATE_IN_ROOM",
	2: "PLAYER_STATE_MATCHING",
	3: "PLAYER_STATE_MATCHED",
	4: "PLAYER_STATE_READY",
	5: "PLAYER_STATE_PLAYING",
}

var PlayerState_value = map[string]int32{
	"PLAYER_STATE_BEGIN":    0,
	"PLAYER_STATE_IN_ROOM":  1,
	"PLAYER_STATE_MATCHING": 2,
	"PLAYER_STATE_MATCHED":  3,
	"PLAYER_STATE_READY":    4,
	"PLAYER_STATE_PLAYING":  5,
}

func (x PlayerState) String() string {
	return proto.EnumName(PlayerState_name, int32(x))
}

func (PlayerState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9af5c0284d6e689a, []int{0}
}

type AssetBaseReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssetBaseReq) Reset()         { *m = AssetBaseReq{} }
func (m *AssetBaseReq) String() string { return proto.CompactTextString(m) }
func (*AssetBaseReq) ProtoMessage()    {}
func (*AssetBaseReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9af5c0284d6e689a, []int{0}
}

func (m *AssetBaseReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetBaseReq.Unmarshal(m, b)
}
func (m *AssetBaseReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetBaseReq.Marshal(b, m, deterministic)
}
func (m *AssetBaseReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetBaseReq.Merge(m, src)
}
func (m *AssetBaseReq) XXX_Size() int {
	return xxx_messageInfo_AssetBaseReq.Size(m)
}
func (m *AssetBaseReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetBaseReq.DiscardUnknown(m)
}

var xxx_messageInfo_AssetBaseReq proto.InternalMessageInfo

func (m *AssetBaseReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type BaseRsp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseRsp) Reset()         { *m = BaseRsp{} }
func (m *BaseRsp) String() string { return proto.CompactTextString(m) }
func (*BaseRsp) ProtoMessage()    {}
func (*BaseRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9af5c0284d6e689a, []int{1}
}

func (m *BaseRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseRsp.Unmarshal(m, b)
}
func (m *BaseRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseRsp.Marshal(b, m, deterministic)
}
func (m *BaseRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseRsp.Merge(m, src)
}
func (m *BaseRsp) XXX_Size() int {
	return xxx_messageInfo_BaseRsp.Size(m)
}
func (m *BaseRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseRsp.DiscardUnknown(m)
}

var xxx_messageInfo_BaseRsp proto.InternalMessageInfo

func (m *BaseRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *BaseRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type CommonRsp struct {
	Rsp                  *BaseRsp `protobuf:"bytes,1,opt,name=rsp,proto3" json:"rsp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonRsp) Reset()         { *m = CommonRsp{} }
func (m *CommonRsp) String() string { return proto.CompactTextString(m) }
func (*CommonRsp) ProtoMessage()    {}
func (*CommonRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9af5c0284d6e689a, []int{2}
}

func (m *CommonRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonRsp.Unmarshal(m, b)
}
func (m *CommonRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonRsp.Marshal(b, m, deterministic)
}
func (m *CommonRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonRsp.Merge(m, src)
}
func (m *CommonRsp) XXX_Size() int {
	return xxx_messageInfo_CommonRsp.Size(m)
}
func (m *CommonRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CommonRsp proto.InternalMessageInfo

func (m *CommonRsp) GetRsp() *BaseRsp {
	if m != nil {
		return m.Rsp
	}
	return nil
}

type GameBaseMsg struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameBaseMsg) Reset()         { *m = GameBaseMsg{} }
func (m *GameBaseMsg) String() string { return proto.CompactTextString(m) }
func (*GameBaseMsg) ProtoMessage()    {}
func (*GameBaseMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_9af5c0284d6e689a, []int{3}
}

func (m *GameBaseMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameBaseMsg.Unmarshal(m, b)
}
func (m *GameBaseMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameBaseMsg.Marshal(b, m, deterministic)
}
func (m *GameBaseMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameBaseMsg.Merge(m, src)
}
func (m *GameBaseMsg) XXX_Size() int {
	return xxx_messageInfo_GameBaseMsg.Size(m)
}
func (m *GameBaseMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_GameBaseMsg.DiscardUnknown(m)
}

var xxx_messageInfo_GameBaseMsg proto.InternalMessageInfo

func (m *GameBaseMsg) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

// 玩家的基本信息
type PlayerInfo struct {
	UserId   int64  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Avatar   string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Nickname string `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	IsBot    bool   `protobuf:"varint,5,opt,name=isBot,proto3" json:"isBot,omitempty"`
	Birthday string `protobuf:"bytes,6,opt,name=birthday,proto3" json:"birthday,omitempty"`
	// 财富值
	AssetScore int64 `protobuf:"varint,7,opt,name=asset_score,json=assetScore,proto3" json:"asset_score,omitempty"`
	// 财富等级, 根据财富值转换得到
	AssetLevel           string   `protobuf:"bytes,8,opt,name=asset_level,json=assetLevel,proto3" json:"asset_level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9af5c0284d6e689a, []int{4}
}

func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(m, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PlayerInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *PlayerInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *PlayerInfo) GetIsBot() bool {
	if m != nil {
		return m.IsBot
	}
	return false
}

func (m *PlayerInfo) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *PlayerInfo) GetAssetScore() int64 {
	if m != nil {
		return m.AssetScore
	}
	return 0
}

func (m *PlayerInfo) GetAssetLevel() string {
	if m != nil {
		return m.AssetLevel
	}
	return ""
}

type RoomInfo struct {
	RoomId  string        `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	OwnerId int64         `protobuf:"varint,2,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	Members []*PlayerInfo `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	// <del>注意下面这个值其实是不变的</del>
	// 这个值可以被自定义规则修改
	Size uint32 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	// 房间匹配类型
	MatchType MatchType `protobuf:"varint,5,opt,name=matchType,proto3,enum=pb.common.MatchType" json:"matchType,omitempty"`
	// 当前房间的房间号，如果没有分配到的话为 -1
	// 目前 roomNum 为四位数字（0000 - 9999）
	RoomNum int32 `protobuf:"varint,6,opt,name=roomNum,proto3" json:"roomNum,omitempty"`
	// 房间的自定义设置, 如果没进行自定义设置改属性无效
	Opt *RoomOption `protobuf:"bytes,7,opt,name=opt,proto3" json:"opt,omitempty"`
	// 房间规则是否修改过, 如果规则修改过在人数满足前不能开始匹配
	OptChanged           bool     `protobuf:"varint,8,opt,name=OptChanged,proto3" json:"OptChanged,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomInfo) Reset()         { *m = RoomInfo{} }
func (m *RoomInfo) String() string { return proto.CompactTextString(m) }
func (*RoomInfo) ProtoMessage()    {}
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9af5c0284d6e689a, []int{5}
}

func (m *RoomInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomInfo.Unmarshal(m, b)
}
func (m *RoomInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomInfo.Marshal(b, m, deterministic)
}
func (m *RoomInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomInfo.Merge(m, src)
}
func (m *RoomInfo) XXX_Size() int {
	return xxx_messageInfo_RoomInfo.Size(m)
}
func (m *RoomInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoomInfo proto.InternalMessageInfo

func (m *RoomInfo) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *RoomInfo) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *RoomInfo) GetMembers() []*PlayerInfo {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *RoomInfo) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *RoomInfo) GetMatchType() MatchType {
	if m != nil {
		return m.MatchType
	}
	return MatchType_UNKNOWN
}

func (m *RoomInfo) GetRoomNum() int32 {
	if m != nil {
		return m.RoomNum
	}
	return 0
}

func (m *RoomInfo) GetOpt() *RoomOption {
	if m != nil {
		return m.Opt
	}
	return nil
}

func (m *RoomInfo) GetOptChanged() bool {
	if m != nil {
		return m.OptChanged
	}
	return false
}

// 房间可设置项目, 现在只支持修改房间人数和游戏时间
//  后续会增加游戏结束规则的设置
type RoomOption struct {
	// 房间大小, [1, 10],
	// 为了房间性能考虑，暂定 10 人上限
	RoomSize int32 `protobuf:"varint,2,opt,name=roomSize,proto3" json:"roomSize,omitempty"`
	// 游戏时长(秒), [300,3600],
	// 游戏全局时间太短的话可能导致游戏错误, 所以不能设置太短
	PlayDuration int32 `protobuf:"varint,3,opt,name=playDuration,proto3" json:"playDuration,omitempty"`
	// 这个房间的地图 id，目前只有单人游戏的房间才能修改地图。
	MapId                int64    `protobuf:"varint,4,opt,name=mapId,proto3" json:"mapId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomOption) Reset()         { *m = RoomOption{} }
func (m *RoomOption) String() string { return proto.CompactTextString(m) }
func (*RoomOption) ProtoMessage()    {}
func (*RoomOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_9af5c0284d6e689a, []int{6}
}

func (m *RoomOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomOption.Unmarshal(m, b)
}
func (m *RoomOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomOption.Marshal(b, m, deterministic)
}
func (m *RoomOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomOption.Merge(m, src)
}
func (m *RoomOption) XXX_Size() int {
	return xxx_messageInfo_RoomOption.Size(m)
}
func (m *RoomOption) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomOption.DiscardUnknown(m)
}

var xxx_messageInfo_RoomOption proto.InternalMessageInfo

func (m *RoomOption) GetRoomSize() int32 {
	if m != nil {
		return m.RoomSize
	}
	return 0
}

func (m *RoomOption) GetPlayDuration() int32 {
	if m != nil {
		return m.PlayDuration
	}
	return 0
}

func (m *RoomOption) GetMapId() int64 {
	if m != nil {
		return m.MapId
	}
	return 0
}

// 等级需要的经验值
type Level struct {
	// 等级
	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	// 等级的最低经验值
	LowExp int64 `protobuf:"varint,2,opt,name=lowExp,proto3" json:"lowExp,omitempty"`
	// 等级的上限经验值
	HighExp              int64    `protobuf:"varint,3,opt,name=highExp,proto3" json:"highExp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Level) Reset()         { *m = Level{} }
func (m *Level) String() string { return proto.CompactTextString(m) }
func (*Level) ProtoMessage()    {}
func (*Level) Descriptor() ([]byte, []int) {
	return fileDescriptor_9af5c0284d6e689a, []int{7}
}

func (m *Level) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Level.Unmarshal(m, b)
}
func (m *Level) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Level.Marshal(b, m, deterministic)
}
func (m *Level) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Level.Merge(m, src)
}
func (m *Level) XXX_Size() int {
	return xxx_messageInfo_Level.Size(m)
}
func (m *Level) XXX_DiscardUnknown() {
	xxx_messageInfo_Level.DiscardUnknown(m)
}

var xxx_messageInfo_Level proto.InternalMessageInfo

func (m *Level) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Level) GetLowExp() int64 {
	if m != nil {
		return m.LowExp
	}
	return 0
}

func (m *Level) GetHighExp() int64 {
	if m != nil {
		return m.HighExp
	}
	return 0
}

// 资产值的字段
type AssetScoreField struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Value                int64    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssetScoreField) Reset()         { *m = AssetScoreField{} }
func (m *AssetScoreField) String() string { return proto.CompactTextString(m) }
func (*AssetScoreField) ProtoMessage()    {}
func (*AssetScoreField) Descriptor() ([]byte, []int) {
	return fileDescriptor_9af5c0284d6e689a, []int{8}
}

func (m *AssetScoreField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetScoreField.Unmarshal(m, b)
}
func (m *AssetScoreField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetScoreField.Marshal(b, m, deterministic)
}
func (m *AssetScoreField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetScoreField.Merge(m, src)
}
func (m *AssetScoreField) XXX_Size() int {
	return xxx_messageInfo_AssetScoreField.Size(m)
}
func (m *AssetScoreField) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetScoreField.DiscardUnknown(m)
}

var xxx_messageInfo_AssetScoreField proto.InternalMessageInfo

func (m *AssetScoreField) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AssetScoreField) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

// 每一局游戏结束后结算的游戏奖励
type GameBonus struct {
	UserID int64 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	// 变化的金币值, 更改前的值 = gold - bonusGold - extraGold
	BonusGold int32 `protobuf:"varint,2,opt,name=bonusGold,proto3" json:"bonusGold,omitempty"`
	// 额外奖励的金币
	ExtraGold int32 `protobuf:"varint,3,opt,name=extraGold,proto3" json:"extraGold,omitempty"`
	// 更新后的金币值
	Gold int32 `protobuf:"varint,4,opt,name=gold,proto3" json:"gold,omitempty"`
	// 奖励经验值, 更改前的值 = exp - bonusExp - extraExp
	BonusExp int32 `protobuf:"varint,5,opt,name=bonusExp,proto3" json:"bonusExp,omitempty"`
	// 额外赠送的经验值
	ExtraExp int32 `protobuf:"varint,6,opt,name=extraExp,proto3" json:"extraExp,omitempty"`
	// 结算奖励的经验值
	Exp int32 `protobuf:"varint,7,opt,name=exp,proto3" json:"exp,omitempty"`
	// 游戏经验结算后,玩家的初始等级和等级增长所覆盖的等级区间
	Levels []*Level `protobuf:"bytes,8,rep,name=levels,proto3" json:"levels,omitempty"`
	// 排位赛的奖励, 由 cenarius 计算后返回
	RankBonus            *GameBonusForRank `protobuf:"bytes,9,opt,name=rankBonus,proto3" json:"rankBonus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GameBonus) Reset()         { *m = GameBonus{} }
func (m *GameBonus) String() string { return proto.CompactTextString(m) }
func (*GameBonus) ProtoMessage()    {}
func (*GameBonus) Descriptor() ([]byte, []int) {
	return fileDescriptor_9af5c0284d6e689a, []int{9}
}

func (m *GameBonus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameBonus.Unmarshal(m, b)
}
func (m *GameBonus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameBonus.Marshal(b, m, deterministic)
}
func (m *GameBonus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameBonus.Merge(m, src)
}
func (m *GameBonus) XXX_Size() int {
	return xxx_messageInfo_GameBonus.Size(m)
}
func (m *GameBonus) XXX_DiscardUnknown() {
	xxx_messageInfo_GameBonus.DiscardUnknown(m)
}

var xxx_messageInfo_GameBonus proto.InternalMessageInfo

func (m *GameBonus) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *GameBonus) GetBonusGold() int32 {
	if m != nil {
		return m.BonusGold
	}
	return 0
}

func (m *GameBonus) GetExtraGold() int32 {
	if m != nil {
		return m.ExtraGold
	}
	return 0
}

func (m *GameBonus) GetGold() int32 {
	if m != nil {
		return m.Gold
	}
	return 0
}

func (m *GameBonus) GetBonusExp() int32 {
	if m != nil {
		return m.BonusExp
	}
	return 0
}

func (m *GameBonus) GetExtraExp() int32 {
	if m != nil {
		return m.ExtraExp
	}
	return 0
}

func (m *GameBonus) GetExp() int32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *GameBonus) GetLevels() []*Level {
	if m != nil {
		return m.Levels
	}
	return nil
}

func (m *GameBonus) GetRankBonus() *GameBonusForRank {
	if m != nil {
		return m.RankBonus
	}
	return nil
}

// 排位奖励, 由 cenarius 计算后返回
type GameBonusForRank struct {
	// 总资产值
	AssetScore int64 `protobuf:"varint,1,opt,name=assetScore,proto3" json:"assetScore,omitempty"`
	// 本局游戏资产值的奖励明细, 使用 repeated 方便以后客户端动态增加条目
	AssetScoreItems []*AssetScoreField `protobuf:"bytes,2,rep,name=assetScoreItems,proto3" json:"assetScoreItems,omitempty"`
	// 资产等级 A5.1
	AssetLevel string `protobuf:"bytes,3,opt,name=assetLevel,proto3" json:"assetLevel,omitempty"`
	// acc 奖励值
	AccBonus string `protobuf:"bytes,4,opt,name=accBonus,proto3" json:"accBonus,omitempty"`
	// acc 总数
	AccTotal             string   `protobuf:"bytes,5,opt,name=accTotal,proto3" json:"accTotal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameBonusForRank) Reset()         { *m = GameBonusForRank{} }
func (m *GameBonusForRank) String() string { return proto.CompactTextString(m) }
func (*GameBonusForRank) ProtoMessage()    {}
func (*GameBonusForRank) Descriptor() ([]byte, []int) {
	return fileDescriptor_9af5c0284d6e689a, []int{9, 0}
}

func (m *GameBonusForRank) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameBonusForRank.Unmarshal(m, b)
}
func (m *GameBonusForRank) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameBonusForRank.Marshal(b, m, deterministic)
}
func (m *GameBonusForRank) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameBonusForRank.Merge(m, src)
}
func (m *GameBonusForRank) XXX_Size() int {
	return xxx_messageInfo_GameBonusForRank.Size(m)
}
func (m *GameBonusForRank) XXX_DiscardUnknown() {
	xxx_messageInfo_GameBonusForRank.DiscardUnknown(m)
}

var xxx_messageInfo_GameBonusForRank proto.InternalMessageInfo

func (m *GameBonusForRank) GetAssetScore() int64 {
	if m != nil {
		return m.AssetScore
	}
	return 0
}

func (m *GameBonusForRank) GetAssetScoreItems() []*AssetScoreField {
	if m != nil {
		return m.AssetScoreItems
	}
	return nil
}

func (m *GameBonusForRank) GetAssetLevel() string {
	if m != nil {
		return m.AssetLevel
	}
	return ""
}

func (m *GameBonusForRank) GetAccBonus() string {
	if m != nil {
		return m.AccBonus
	}
	return ""
}

func (m *GameBonusForRank) GetAccTotal() string {
	if m != nil {
		return m.AccTotal
	}
	return ""
}

type PaginationReq struct {
	// 分页的页数，从 1 开始，如果不传的话默认为 1
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// 每页的条数，如果不传的话默认为 20
	// 注意不同的接口对 perPage 的最大值可能有自己的限制
	// 具体要参考对应接口的文档
	PerPage              int32    `protobuf:"varint,2,opt,name=perPage,proto3" json:"perPage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaginationReq) Reset()         { *m = PaginationReq{} }
func (m *PaginationReq) String() string { return proto.CompactTextString(m) }
func (*PaginationReq) ProtoMessage()    {}
func (*PaginationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9af5c0284d6e689a, []int{10}
}

func (m *PaginationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaginationReq.Unmarshal(m, b)
}
func (m *PaginationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaginationReq.Marshal(b, m, deterministic)
}
func (m *PaginationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaginationReq.Merge(m, src)
}
func (m *PaginationReq) XXX_Size() int {
	return xxx_messageInfo_PaginationReq.Size(m)
}
func (m *PaginationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PaginationReq.DiscardUnknown(m)
}

var xxx_messageInfo_PaginationReq proto.InternalMessageInfo

func (m *PaginationReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PaginationReq) GetPerPage() int32 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

type PaginationRsp struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage              int32    `protobuf:"varint,2,opt,name=perPage,proto3" json:"perPage,omitempty"`
	TotalCount           int32    `protobuf:"varint,3,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	TotalPages           int32    `protobuf:"varint,4,opt,name=totalPages,proto3" json:"totalPages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaginationRsp) Reset()         { *m = PaginationRsp{} }
func (m *PaginationRsp) String() string { return proto.CompactTextString(m) }
func (*PaginationRsp) ProtoMessage()    {}
func (*PaginationRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9af5c0284d6e689a, []int{11}
}

func (m *PaginationRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaginationRsp.Unmarshal(m, b)
}
func (m *PaginationRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaginationRsp.Marshal(b, m, deterministic)
}
func (m *PaginationRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaginationRsp.Merge(m, src)
}
func (m *PaginationRsp) XXX_Size() int {
	return xxx_messageInfo_PaginationRsp.Size(m)
}
func (m *PaginationRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PaginationRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PaginationRsp proto.InternalMessageInfo

func (m *PaginationRsp) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PaginationRsp) GetPerPage() int32 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *PaginationRsp) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *PaginationRsp) GetTotalPages() int32 {
	if m != nil {
		return m.TotalPages
	}
	return 0
}

type DetailValue struct {
	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code  string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Value int64  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	// Scenario.Category
	Category string `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	// 单价 Scenario.C_Price
	UnitPrice int64 `protobuf:"varint,5,opt,name=unitPrice,proto3" json:"unitPrice,omitempty"`
	// 负债 Scenario.C_Liabilities()
	Liabilities int64 `protobuf:"varint,6,opt,name=liabilities,proto3" json:"liabilities,omitempty"`
	// 收入 Scenario.C_Income()
	Income int64 `protobuf:"varint,7,opt,name=income,proto3" json:"income,omitempty"`
	// 支出 Scenario.C_Interest()
	Expense int64 `protobuf:"varint,8,opt,name=expense,proto3" json:"expense,omitempty"`
	// Scenario.C_Shard
	Shard int64 `protobuf:"varint,9,opt,name=shard,proto3" json:"shard,omitempty"`
	// 2室1厅 Shard=2 , Mark = 1,	Scenario.C_Mark
	Mark                 int64    `protobuf:"varint,10,opt,name=mark,proto3" json:"mark,omitempty"`
	ImgFile              string   `protobuf:"bytes,11,opt,name=imgFile,proto3" json:"imgFile,omitempty"`
	Desc                 string   `protobuf:"bytes,12,opt,name=desc,proto3" json:"desc,omitempty"`
	DownPayment          int64    `protobuf:"varint,13,opt,name=downPayment,proto3" json:"downPayment,omitempty"`
	DownPaymentPCT       float32  `protobuf:"fixed32,14,opt,name=downPaymentPCT,proto3" json:"downPaymentPCT,omitempty"`
	InterestRatePCT      float32  `protobuf:"fixed32,15,opt,name=interestRatePCT,proto3" json:"interestRatePCT,omitempty"`
	YieldRatePCT         float32  `protobuf:"fixed32,16,opt,name=yieldRatePCT,proto3" json:"yieldRatePCT,omitempty"`
	HighPrice            int64    `protobuf:"varint,17,opt,name=highPrice,proto3" json:"highPrice,omitempty"`
	LowPrice             int64    `protobuf:"varint,18,opt,name=lowPrice,proto3" json:"lowPrice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailValue) Reset()         { *m = DetailValue{} }
func (m *DetailValue) String() string { return proto.CompactTextString(m) }
func (*DetailValue) ProtoMessage()    {}
func (*DetailValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_9af5c0284d6e689a, []int{12}
}

func (m *DetailValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailValue.Unmarshal(m, b)
}
func (m *DetailValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailValue.Marshal(b, m, deterministic)
}
func (m *DetailValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailValue.Merge(m, src)
}
func (m *DetailValue) XXX_Size() int {
	return xxx_messageInfo_DetailValue.Size(m)
}
func (m *DetailValue) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailValue.DiscardUnknown(m)
}

var xxx_messageInfo_DetailValue proto.InternalMessageInfo

func (m *DetailValue) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DetailValue) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *DetailValue) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *DetailValue) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *DetailValue) GetUnitPrice() int64 {
	if m != nil {
		return m.UnitPrice
	}
	return 0
}

func (m *DetailValue) GetLiabilities() int64 {
	if m != nil {
		return m.Liabilities
	}
	return 0
}

func (m *DetailValue) GetIncome() int64 {
	if m != nil {
		return m.Income
	}
	return 0
}

func (m *DetailValue) GetExpense() int64 {
	if m != nil {
		return m.Expense
	}
	return 0
}

func (m *DetailValue) GetShard() int64 {
	if m != nil {
		return m.Shard
	}
	return 0
}

func (m *DetailValue) GetMark() int64 {
	if m != nil {
		return m.Mark
	}
	return 0
}

func (m *DetailValue) GetImgFile() string {
	if m != nil {
		return m.ImgFile
	}
	return ""
}

func (m *DetailValue) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *DetailValue) GetDownPayment() int64 {
	if m != nil {
		return m.DownPayment
	}
	return 0
}

func (m *DetailValue) GetDownPaymentPCT() float32 {
	if m != nil {
		return m.DownPaymentPCT
	}
	return 0
}

func (m *DetailValue) GetInterestRatePCT() float32 {
	if m != nil {
		return m.InterestRatePCT
	}
	return 0
}

func (m *DetailValue) GetYieldRatePCT() float32 {
	if m != nil {
		return m.YieldRatePCT
	}
	return 0
}

func (m *DetailValue) GetHighPrice() int64 {
	if m != nil {
		return m.HighPrice
	}
	return 0
}

func (m *DetailValue) GetLowPrice() int64 {
	if m != nil {
		return m.LowPrice
	}
	return 0
}

type TopCategory struct {
	Category             string         `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Code                 string         `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Details              []*DetailValue `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TopCategory) Reset()         { *m = TopCategory{} }
func (m *TopCategory) String() string { return proto.CompactTextString(m) }
func (*TopCategory) ProtoMessage()    {}
func (*TopCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_9af5c0284d6e689a, []int{13}
}

func (m *TopCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopCategory.Unmarshal(m, b)
}
func (m *TopCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopCategory.Marshal(b, m, deterministic)
}
func (m *TopCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopCategory.Merge(m, src)
}
func (m *TopCategory) XXX_Size() int {
	return xxx_messageInfo_TopCategory.Size(m)
}
func (m *TopCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_TopCategory.DiscardUnknown(m)
}

var xxx_messageInfo_TopCategory proto.InternalMessageInfo

func (m *TopCategory) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *TopCategory) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *TopCategory) GetDetails() []*DetailValue {
	if m != nil {
		return m.Details
	}
	return nil
}

//现金流量表
type CashFlowStatement struct {
	Total                int64          `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Details              []*DetailValue `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CashFlowStatement) Reset()         { *m = CashFlowStatement{} }
func (m *CashFlowStatement) String() string { return proto.CompactTextString(m) }
func (*CashFlowStatement) ProtoMessage()    {}
func (*CashFlowStatement) Descriptor() ([]byte, []int) {
	return fileDescriptor_9af5c0284d6e689a, []int{14}
}

func (m *CashFlowStatement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CashFlowStatement.Unmarshal(m, b)
}
func (m *CashFlowStatement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CashFlowStatement.Marshal(b, m, deterministic)
}
func (m *CashFlowStatement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CashFlowStatement.Merge(m, src)
}
func (m *CashFlowStatement) XXX_Size() int {
	return xxx_messageInfo_CashFlowStatement.Size(m)
}
func (m *CashFlowStatement) XXX_DiscardUnknown() {
	xxx_messageInfo_CashFlowStatement.DiscardUnknown(m)
}

var xxx_messageInfo_CashFlowStatement proto.InternalMessageInfo

func (m *CashFlowStatement) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *CashFlowStatement) GetDetails() []*DetailValue {
	if m != nil {
		return m.Details
	}
	return nil
}

//资产负债表
type AssetLiabilityStatement struct {
	AssetTotal           int64          `protobuf:"varint,1,opt,name=assetTotal,proto3" json:"assetTotal,omitempty"`
	DebtsTotal           int64          `protobuf:"varint,2,opt,name=debtsTotal,proto3" json:"debtsTotal,omitempty"`
	Assets               []*TopCategory `protobuf:"bytes,3,rep,name=assets,proto3" json:"assets,omitempty"`
	Debts                []*TopCategory `protobuf:"bytes,4,rep,name=debts,proto3" json:"debts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AssetLiabilityStatement) Reset()         { *m = AssetLiabilityStatement{} }
func (m *AssetLiabilityStatement) String() string { return proto.CompactTextString(m) }
func (*AssetLiabilityStatement) ProtoMessage()    {}
func (*AssetLiabilityStatement) Descriptor() ([]byte, []int) {
	return fileDescriptor_9af5c0284d6e689a, []int{15}
}

func (m *AssetLiabilityStatement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetLiabilityStatement.Unmarshal(m, b)
}
func (m *AssetLiabilityStatement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetLiabilityStatement.Marshal(b, m, deterministic)
}
func (m *AssetLiabilityStatement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetLiabilityStatement.Merge(m, src)
}
func (m *AssetLiabilityStatement) XXX_Size() int {
	return xxx_messageInfo_AssetLiabilityStatement.Size(m)
}
func (m *AssetLiabilityStatement) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetLiabilityStatement.DiscardUnknown(m)
}

var xxx_messageInfo_AssetLiabilityStatement proto.InternalMessageInfo

func (m *AssetLiabilityStatement) GetAssetTotal() int64 {
	if m != nil {
		return m.AssetTotal
	}
	return 0
}

func (m *AssetLiabilityStatement) GetDebtsTotal() int64 {
	if m != nil {
		return m.DebtsTotal
	}
	return 0
}

func (m *AssetLiabilityStatement) GetAssets() []*TopCategory {
	if m != nil {
		return m.Assets
	}
	return nil
}

func (m *AssetLiabilityStatement) GetDebts() []*TopCategory {
	if m != nil {
		return m.Debts
	}
	return nil
}

//损益表
type MonthProfitLossStatement struct {
	// 总收入
	Income int64 `protobuf:"varint,1,opt,name=income,proto3" json:"income,omitempty"`
	// 总支出
	Expense int64 `protobuf:"varint,2,opt,name=expense,proto3" json:"expense,omitempty"`
	// 月现金流 = 总收入 - 总支出
	Cashflow             int64          `protobuf:"varint,3,opt,name=cashflow,proto3" json:"cashflow,omitempty"`
	IncomeTops           []*TopCategory `protobuf:"bytes,4,rep,name=incomeTops,proto3" json:"incomeTops,omitempty"`
	ExpenseTops          []*TopCategory `protobuf:"bytes,5,rep,name=expenseTops,proto3" json:"expenseTops,omitempty"`
	CashflowTops         []*TopCategory `protobuf:"bytes,6,rep,name=cashflowTops,proto3" json:"cashflowTops,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MonthProfitLossStatement) Reset()         { *m = MonthProfitLossStatement{} }
func (m *MonthProfitLossStatement) String() string { return proto.CompactTextString(m) }
func (*MonthProfitLossStatement) ProtoMessage()    {}
func (*MonthProfitLossStatement) Descriptor() ([]byte, []int) {
	return fileDescriptor_9af5c0284d6e689a, []int{16}
}

func (m *MonthProfitLossStatement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonthProfitLossStatement.Unmarshal(m, b)
}
func (m *MonthProfitLossStatement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonthProfitLossStatement.Marshal(b, m, deterministic)
}
func (m *MonthProfitLossStatement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonthProfitLossStatement.Merge(m, src)
}
func (m *MonthProfitLossStatement) XXX_Size() int {
	return xxx_messageInfo_MonthProfitLossStatement.Size(m)
}
func (m *MonthProfitLossStatement) XXX_DiscardUnknown() {
	xxx_messageInfo_MonthProfitLossStatement.DiscardUnknown(m)
}

var xxx_messageInfo_MonthProfitLossStatement proto.InternalMessageInfo

func (m *MonthProfitLossStatement) GetIncome() int64 {
	if m != nil {
		return m.Income
	}
	return 0
}

func (m *MonthProfitLossStatement) GetExpense() int64 {
	if m != nil {
		return m.Expense
	}
	return 0
}

func (m *MonthProfitLossStatement) GetCashflow() int64 {
	if m != nil {
		return m.Cashflow
	}
	return 0
}

func (m *MonthProfitLossStatement) GetIncomeTops() []*TopCategory {
	if m != nil {
		return m.IncomeTops
	}
	return nil
}

func (m *MonthProfitLossStatement) GetExpenseTops() []*TopCategory {
	if m != nil {
		return m.ExpenseTops
	}
	return nil
}

func (m *MonthProfitLossStatement) GetCashflowTops() []*TopCategory {
	if m != nil {
		return m.CashflowTops
	}
	return nil
}

// 财务报表
type AssetStatement struct {
	// 财富自由度
	Degree float32 `protobuf:"fixed32,1,opt,name=degree,proto3" json:"degree,omitempty"`
	// 现金流量表
	CashFlow *CashFlowStatement `protobuf:"bytes,2,opt,name=cashFlow,proto3" json:"cashFlow,omitempty"`
	// 资产负债表
	AssetLiability *AssetLiabilityStatement `protobuf:"bytes,3,opt,name=assetLiability,proto3" json:"assetLiability,omitempty"`
	// 损益表
	MonthProfitLoss      *MonthProfitLossStatement `protobuf:"bytes,4,opt,name=monthProfitLoss,proto3" json:"monthProfitLoss,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *AssetStatement) Reset()         { *m = AssetStatement{} }
func (m *AssetStatement) String() string { return proto.CompactTextString(m) }
func (*AssetStatement) ProtoMessage()    {}
func (*AssetStatement) Descriptor() ([]byte, []int) {
	return fileDescriptor_9af5c0284d6e689a, []int{17}
}

func (m *AssetStatement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetStatement.Unmarshal(m, b)
}
func (m *AssetStatement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetStatement.Marshal(b, m, deterministic)
}
func (m *AssetStatement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetStatement.Merge(m, src)
}
func (m *AssetStatement) XXX_Size() int {
	return xxx_messageInfo_AssetStatement.Size(m)
}
func (m *AssetStatement) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetStatement.DiscardUnknown(m)
}

var xxx_messageInfo_AssetStatement proto.InternalMessageInfo

func (m *AssetStatement) GetDegree() float32 {
	if m != nil {
		return m.Degree
	}
	return 0
}

func (m *AssetStatement) GetCashFlow() *CashFlowStatement {
	if m != nil {
		return m.CashFlow
	}
	return nil
}

func (m *AssetStatement) GetAssetLiability() *AssetLiabilityStatement {
	if m != nil {
		return m.AssetLiability
	}
	return nil
}

func (m *AssetStatement) GetMonthProfitLoss() *MonthProfitLossStatement {
	if m != nil {
		return m.MonthProfitLoss
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.common.PlayerState", PlayerState_name, PlayerState_value)
	proto.RegisterType((*AssetBaseReq)(nil), "pb.common.AssetBaseReq")
	proto.RegisterType((*BaseRsp)(nil), "pb.common.BaseRsp")
	proto.RegisterType((*CommonRsp)(nil), "pb.common.CommonRsp")
	proto.RegisterType((*GameBaseMsg)(nil), "pb.common.GameBaseMsg")
	proto.RegisterType((*PlayerInfo)(nil), "pb.common.PlayerInfo")
	proto.RegisterType((*RoomInfo)(nil), "pb.common.RoomInfo")
	proto.RegisterType((*RoomOption)(nil), "pb.common.RoomOption")
	proto.RegisterType((*Level)(nil), "pb.common.Level")
	proto.RegisterType((*AssetScoreField)(nil), "pb.common.AssetScoreField")
	proto.RegisterType((*GameBonus)(nil), "pb.common.GameBonus")
	proto.RegisterType((*GameBonusForRank)(nil), "pb.common.GameBonus.forRank")
	proto.RegisterType((*PaginationReq)(nil), "pb.common.PaginationReq")
	proto.RegisterType((*PaginationRsp)(nil), "pb.common.PaginationRsp")
	proto.RegisterType((*DetailValue)(nil), "pb.common.DetailValue")
	proto.RegisterType((*TopCategory)(nil), "pb.common.TopCategory")
	proto.RegisterType((*CashFlowStatement)(nil), "pb.common.CashFlowStatement")
	proto.RegisterType((*AssetLiabilityStatement)(nil), "pb.common.AssetLiabilityStatement")
	proto.RegisterType((*MonthProfitLossStatement)(nil), "pb.common.MonthProfitLossStatement")
	proto.RegisterType((*AssetStatement)(nil), "pb.common.AssetStatement")
}

func init() { proto.RegisterFile("common/types.proto", fileDescriptor_9af5c0284d6e689a) }

var fileDescriptor_9af5c0284d6e689a = []byte{
	// 1368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x57, 0xdd, 0x6e, 0x23, 0xc5,
	0x12, 0x3e, 0xf6, 0xd8, 0x49, 0x5c, 0xce, 0x26, 0xde, 0x3e, 0xbb, 0x7b, 0xe6, 0x44, 0x2b, 0x88,
	0x06, 0x58, 0x2c, 0x04, 0x09, 0x04, 0x09, 0xad, 0x56, 0xda, 0x8b, 0xfc, 0x6d, 0x30, 0xca, 0x8f,
	0xd5, 0xb1, 0x90, 0x16, 0x2e, 0xa2, 0xb6, 0xdd, 0xb1, 0x47, 0x99, 0x99, 0x1e, 0xa6, 0xdb, 0x49,
	0x8c, 0xc4, 0x15, 0xef, 0x80, 0x78, 0x02, 0x5e, 0x81, 0x47, 0xe0, 0x86, 0x57, 0xe1, 0x11, 0x90,
	0x50, 0x55, 0xf7, 0x8c, 0xc7, 0xce, 0x66, 0xd9, 0xbb, 0xfe, 0xaa, 0xbe, 0xea, 0xae, 0xff, 0xb1,
	0x81, 0x0d, 0x54, 0x1c, 0xab, 0x64, 0xdb, 0x4c, 0x53, 0xa9, 0xb7, 0xd2, 0x4c, 0x19, 0xc5, 0x1a,
	0x69, 0x7f, 0xcb, 0x8a, 0x37, 0xfe, 0xeb, 0xd4, 0x03, 0x95, 0x68, 0xe3, 0xf4, 0xc1, 0x33, 0x58,
	0xdd, 0xd5, 0x5a, 0x9a, 0x3d, 0xa1, 0x25, 0x97, 0x3f, 0xb0, 0x27, 0xb0, 0x34, 0xd1, 0x32, 0xeb,
	0x0c, 0xfd, 0xca, 0x66, 0xa5, 0xed, 0x71, 0x87, 0x82, 0x6d, 0x58, 0x26, 0x8a, 0x4e, 0x19, 0x83,
	0xda, 0x40, 0x0d, 0x25, 0x11, 0xea, 0x9c, 0xce, 0xac, 0x05, 0x5e, 0xac, 0x47, 0x7e, 0x75, 0xb3,
	0xd2, 0x6e, 0x70, 0x3c, 0x06, 0x5f, 0x40, 0x63, 0x9f, 0xde, 0x43, 0x93, 0x0f, 0xc1, 0xcb, 0x74,
	0x4a, 0x16, 0xcd, 0x1d, 0xb6, 0x55, 0xf8, 0xb4, 0xe5, 0xee, 0xe4, 0xa8, 0x0e, 0x3e, 0x82, 0xe6,
	0x91, 0x88, 0x25, 0xca, 0x4e, 0xf4, 0xe8, 0x5e, 0x57, 0xfe, 0xac, 0x00, 0x74, 0x23, 0x31, 0x95,
	0x59, 0x27, 0xb9, 0x54, 0xf7, 0xd1, 0x50, 0x2e, 0xae, 0x85, 0x11, 0x99, 0xef, 0x91, 0x57, 0x0e,
	0xb1, 0x0d, 0x58, 0x49, 0xc2, 0xc1, 0x55, 0x22, 0x62, 0xe9, 0xd7, 0x48, 0x53, 0x60, 0xf6, 0x08,
	0xea, 0xa1, 0xde, 0x53, 0xc6, 0xaf, 0x6f, 0x56, 0xda, 0x2b, 0xdc, 0x02, 0xb4, 0xe8, 0x87, 0x99,
	0x19, 0x0f, 0xc5, 0xd4, 0x5f, 0xb2, 0x16, 0x39, 0x66, 0xef, 0x43, 0x53, 0x60, 0xfe, 0x2e, 0xf4,
	0x40, 0x65, 0xd2, 0x5f, 0x26, 0x17, 0x80, 0x44, 0xe7, 0x28, 0x99, 0x11, 0x22, 0x79, 0x2d, 0x23,
	0x7f, 0x85, 0xec, 0x2d, 0xe1, 0x18, 0x25, 0xc1, 0xaf, 0x55, 0x58, 0xe1, 0x4a, 0xc5, 0x79, 0x30,
	0x19, 0x9e, 0x6d, 0x30, 0x0d, 0xee, 0x10, 0xf3, 0x61, 0x59, 0xdd, 0x24, 0x14, 0x65, 0x95, 0x9e,
	0xc8, 0x21, 0xdb, 0x86, 0xe5, 0x58, 0xc6, 0x7d, 0x99, 0x69, 0xdf, 0xdb, 0xf4, 0xda, 0xcd, 0x9d,
	0xc7, 0xa5, 0xf4, 0xce, 0xd2, 0xc4, 0x73, 0x16, 0x96, 0x4f, 0x87, 0x3f, 0xda, 0xd8, 0x1f, 0x70,
	0x3a, 0xb3, 0x1d, 0x68, 0xc4, 0xc2, 0x0c, 0xc6, 0xbd, 0x69, 0x2a, 0x29, 0xf6, 0xb5, 0x9d, 0x47,
	0xa5, 0x6b, 0x4e, 0x72, 0x1d, 0x9f, 0xd1, 0xd0, 0x25, 0x74, 0xee, 0x74, 0x12, 0x53, 0x52, 0xea,
	0x3c, 0x87, 0xec, 0x63, 0xf0, 0x54, 0x6a, 0x28, 0x17, 0xf3, 0xee, 0x60, 0x98, 0x67, 0xa9, 0x09,
	0x55, 0xc2, 0x91, 0xc1, 0xde, 0x03, 0x38, 0x4b, 0xcd, 0xfe, 0x58, 0x24, 0x23, 0x39, 0xa4, 0xd4,
	0xac, 0xf0, 0x92, 0x24, 0xe8, 0x03, 0xcc, 0x4c, 0xb0, 0x0c, 0xf8, 0xc2, 0x39, 0x3a, 0x5f, 0xa5,
	0x17, 0x0b, 0xcc, 0x02, 0x58, 0x4d, 0x23, 0x31, 0x3d, 0x98, 0x64, 0x02, 0xb9, 0x54, 0xf2, 0x3a,
	0x9f, 0x93, 0x61, 0x71, 0x63, 0x91, 0x76, 0x86, 0x14, 0xb9, 0xc7, 0x2d, 0x08, 0xce, 0xa0, 0x4e,
	0x75, 0x40, 0xf5, 0xb5, 0x88, 0x26, 0xd2, 0xb5, 0x91, 0x05, 0x58, 0x90, 0x48, 0xdd, 0x1c, 0xde,
	0xa6, 0x2e, 0xef, 0x0e, 0x61, 0xf4, 0xe3, 0x70, 0x34, 0x46, 0x85, 0x67, 0x0b, 0xe2, 0x60, 0xf0,
	0x12, 0xd6, 0x77, 0x8b, 0xf2, 0xbf, 0x0a, 0x65, 0x34, 0xc4, 0xab, 0x4d, 0x68, 0x22, 0xe9, 0x8a,
	0x6a, 0xc1, 0xec, 0xc1, 0x6a, 0xe9, 0xc1, 0xe0, 0x2f, 0x0f, 0x1a, 0x34, 0x05, 0x2a, 0x99, 0xe8,
	0xa2, 0xb9, 0x0f, 0xe6, 0x9a, 0xfb, 0x80, 0x3d, 0x85, 0x46, 0x1f, 0x09, 0x47, 0x2a, 0x1a, 0xba,
	0x64, 0xcc, 0x04, 0xa8, 0x95, 0xb7, 0x26, 0x13, 0xa4, 0xb5, 0xa9, 0x98, 0x09, 0xb0, 0x01, 0x46,
	0xa8, 0xa8, 0xd9, 0xf9, 0xc5, 0x33, 0xb5, 0x38, 0x9a, 0x63, 0x3c, 0x75, 0x9b, 0xdb, 0x1c, 0xa3,
	0x8e, 0x8c, 0x51, 0x67, 0x2b, 0x5d, 0x60, 0x9c, 0x7b, 0x79, 0x9b, 0x52, 0xa9, 0xeb, 0x1c, 0x8f,
	0xac, 0x0d, 0x4b, 0xd4, 0xe9, 0xda, 0x5f, 0xa1, 0x76, 0x6c, 0x95, 0xea, 0x4f, 0x89, 0xe6, 0x4e,
	0xcf, 0x5e, 0x40, 0x23, 0x13, 0xc9, 0x15, 0x05, 0xea, 0x37, 0xa8, 0x59, 0x9e, 0x96, 0xc8, 0x45,
	0x12, 0xb6, 0x2e, 0x55, 0xc6, 0x45, 0x72, 0xc5, 0x67, 0xf4, 0x8d, 0x3f, 0x2a, 0xb0, 0xec, 0xc4,
	0xd8, 0x45, 0xb3, 0x79, 0x73, 0x79, 0x2a, 0x4f, 0xe0, 0x01, 0xac, 0xcf, 0x50, 0xc7, 0xc8, 0x58,
	0xfb, 0x55, 0x72, 0x6d, 0xa3, 0xf4, 0xda, 0x42, 0xc9, 0xf8, 0xa2, 0x49, 0xf1, 0x0a, 0xc5, 0xe0,
	0x56, 0x4a, 0x49, 0x82, 0x59, 0x12, 0x83, 0x81, 0x0d, 0xc6, 0xad, 0x95, 0x1c, 0x3b, 0x5d, 0x4f,
	0x19, 0x11, 0x51, 0x76, 0xad, 0x8e, 0x70, 0xf0, 0x12, 0x1e, 0x74, 0xc5, 0x28, 0x4c, 0xa8, 0x47,
	0x71, 0x03, 0x33, 0xa8, 0xa5, 0x62, 0x54, 0xac, 0x57, 0x3c, 0x63, 0xb7, 0xa5, 0x32, 0xeb, 0xa2,
	0xd8, 0x16, 0x3b, 0x87, 0xc1, 0x4f, 0x73, 0xe6, 0x76, 0x3b, 0xbf, 0xbb, 0x39, 0x46, 0x65, 0xd0,
	0x8d, 0x7d, 0x35, 0x49, 0x8c, 0x6b, 0x95, 0x92, 0xa4, 0xd0, 0x23, 0x59, 0xbb, 0x8e, 0x29, 0x49,
	0x82, 0x9f, 0x6b, 0xd0, 0x3c, 0x90, 0x46, 0x84, 0xd1, 0xb7, 0x34, 0x2e, 0x0c, 0x6a, 0xb4, 0x58,
	0x6d, 0xa3, 0xd3, 0xb9, 0xf8, 0x5e, 0xd8, 0x8f, 0x83, 0xfd, 0x5e, 0x14, 0xbd, 0xef, 0x95, 0x87,
	0x6d, 0x03, 0x56, 0x06, 0xc2, 0xc8, 0x91, 0xca, 0xa6, 0x79, 0x0e, 0x73, 0x8c, 0x3d, 0x3d, 0x49,
	0x42, 0xd3, 0xcd, 0xc2, 0x81, 0x5d, 0x51, 0x1e, 0x9f, 0x09, 0xd8, 0x26, 0x34, 0xa3, 0x50, 0xf4,
	0xc3, 0x28, 0x34, 0xa1, 0xd4, 0xd4, 0xa6, 0x1e, 0x2f, 0x8b, 0x70, 0x92, 0xc2, 0x64, 0xa0, 0xe2,
	0x7c, 0x47, 0x3b, 0x84, 0xb9, 0x91, 0xb7, 0xa9, 0x4c, 0xb4, 0xa4, 0x05, 0xe4, 0xf1, 0x1c, 0xa2,
	0x8f, 0x7a, 0x2c, 0xb2, 0x21, 0xf5, 0xa6, 0xc7, 0x2d, 0xc0, 0x68, 0x62, 0x91, 0x5d, 0xf9, 0x40,
	0x42, 0x3a, 0xe3, 0x1d, 0x61, 0x3c, 0x7a, 0x15, 0x46, 0xd2, 0x6f, 0x92, 0xdb, 0x39, 0x44, 0xf6,
	0x50, 0xea, 0x81, 0xbf, 0x6a, 0x63, 0xc7, 0x33, 0xfa, 0x3a, 0x54, 0x37, 0x49, 0x57, 0x4c, 0x63,
	0x99, 0x18, 0xff, 0x81, 0xf5, 0xb5, 0x24, 0x62, 0xcf, 0x60, 0xad, 0x04, 0xbb, 0xfb, 0x3d, 0x7f,
	0x6d, 0xb3, 0xd2, 0xae, 0xf2, 0x05, 0x29, 0x6b, 0xc3, 0x7a, 0x98, 0x18, 0x99, 0x49, 0x6d, 0xb8,
	0x30, 0x12, 0x89, 0xeb, 0x44, 0x5c, 0x14, 0xe3, 0x7e, 0x9c, 0x52, 0x5f, 0x3b, 0x5a, 0x8b, 0x68,
	0x73, 0x32, 0xcc, 0x30, 0xee, 0x30, 0x9b, 0xe1, 0x87, 0x36, 0xc3, 0x85, 0x00, 0x6b, 0x13, 0xa9,
	0x1b, 0xab, 0x64, 0xa4, 0x2c, 0x70, 0xa0, 0xa0, 0xd9, 0x53, 0xe9, 0x7e, 0x5e, 0xaa, 0x72, 0x19,
	0x2b, 0x0b, 0x65, 0x7c, 0x53, 0x33, 0x7c, 0x0e, 0xcb, 0x43, 0xea, 0xa1, 0xfc, 0x13, 0xf6, 0xa4,
	0x34, 0x98, 0xa5, 0xee, 0xe2, 0x39, 0x2d, 0xf8, 0x1e, 0x1e, 0xee, 0x0b, 0x3d, 0x7e, 0x15, 0xa9,
	0x9b, 0x73, 0x23, 0x8c, 0xa4, 0xac, 0xe1, 0x96, 0xa5, 0x11, 0x73, 0x0b, 0x9c, 0x40, 0xf9, 0xf2,
	0xea, 0xbb, 0x5d, 0xfe, 0x7b, 0x05, 0xfe, 0x47, 0xeb, 0xe0, 0xd8, 0xb5, 0xcf, 0x74, 0xf6, 0x46,
	0xbe, 0x05, 0x7a, 0xa5, 0x87, 0x4a, 0x12, 0xd4, 0x0f, 0x65, 0xdf, 0x68, 0xab, 0xb7, 0x8b, 0xbd,
	0x24, 0x61, 0x5b, 0xb0, 0x44, 0xec, 0x37, 0x45, 0x5a, 0x4a, 0x21, 0x77, 0x2c, 0xf6, 0x29, 0xd4,
	0xc9, 0xda, 0xaf, 0xbd, 0x95, 0x6e, 0x49, 0xc1, 0x2f, 0x55, 0xf0, 0x4f, 0x54, 0x62, 0xc6, 0xdd,
	0x4c, 0x5d, 0x86, 0xe6, 0x58, 0x69, 0x3d, 0x73, 0x7d, 0x36, 0x00, 0x95, 0xfb, 0x06, 0xa0, 0x3a,
	0x3f, 0x00, 0x54, 0x47, 0x3d, 0xbe, 0x8c, 0xd4, 0x8d, 0x9b, 0xd3, 0x02, 0xb3, 0xaf, 0x00, 0xac,
	0x7d, 0x4f, 0xa5, 0xff, 0xe6, 0x5d, 0x89, 0xc9, 0x9e, 0x43, 0xd3, 0x5d, 0x4f, 0x86, 0xf5, 0xb7,
	0x1a, 0x96, 0xa9, 0xec, 0x05, 0xac, 0xe6, 0xaf, 0x93, 0xe9, 0xd2, 0x5b, 0x4d, 0xe7, 0xb8, 0xc1,
	0xdf, 0x15, 0x58, 0xb3, 0x1b, 0xbe, 0x9c, 0x8e, 0xa1, 0x1c, 0x65, 0xd2, 0xa6, 0xa3, 0xca, 0x1d,
	0x62, 0xcf, 0x6d, 0xd0, 0xd8, 0x5a, 0x94, 0x8f, 0xf9, 0x8f, 0xd2, 0x9d, 0xae, 0xe3, 0x05, 0x9b,
	0x7d, 0x03, 0x6b, 0x62, 0xae, 0x6d, 0x28, 0x69, 0xcd, 0x9d, 0x60, 0xf1, 0x33, 0x73, 0xb7, 0xaf,
	0xf8, 0x82, 0x25, 0x3b, 0x81, 0xf5, 0x78, 0xbe, 0x90, 0xb4, 0x10, 0x9b, 0x3b, 0x1f, 0x94, 0x7f,
	0x96, 0xdd, 0x53, 0x6a, 0xbe, 0x68, 0xfb, 0xc9, 0x6f, 0x15, 0x68, 0xda, 0xdf, 0x82, 0x44, 0x62,
	0x4f, 0x80, 0x75, 0x8f, 0x77, 0x5f, 0x1f, 0xf2, 0x8b, 0xf3, 0xde, 0x6e, 0xef, 0xf0, 0x62, 0xef,
	0xf0, 0xa8, 0x73, 0xda, 0xfa, 0x0f, 0xf3, 0xe1, 0xd1, 0x9c, 0xbc, 0x73, 0x7a, 0xc1, 0xcf, 0xce,
	0x4e, 0x5a, 0x15, 0xf6, 0x7f, 0x78, 0x3c, 0xa7, 0x39, 0xd9, 0xed, 0xed, 0x7f, 0xdd, 0x39, 0x3d,
	0x6a, 0x55, 0xef, 0x18, 0x91, 0xea, 0xf0, 0xa0, 0xe5, 0xdd, 0x79, 0x86, 0x1f, 0xee, 0x1e, 0xbc,
	0x6e, 0xd5, 0xee, 0x58, 0x20, 0xc0, 0xbb, 0xea, 0x7b, 0xed, 0xef, 0x9e, 0x8d, 0x42, 0x13, 0x09,
	0x8a, 0x71, 0xfb, 0x5a, 0x0e, 0x8c, 0xca, 0x26, 0xe9, 0x36, 0x65, 0xe7, 0xb3, 0xb4, 0xbf, 0x3d,
	0x52, 0xdb, 0x36, 0xf8, 0xfe, 0x12, 0xfd, 0x7f, 0xf9, 0xf2, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xc9, 0x4f, 0xf8, 0x76, 0xf5, 0x0c, 0x00, 0x00,
}
