// Code generated by protoc-gen-go. DO NOT EDIT.
// source: strange/strange.proto

package strange

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 雇佣新的机器人
type HireStrangeReq struct {
	// 房间大小
	Size int64 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	// 每个房间的机器人数量
	Per int64 `protobuf:"varint,2,opt,name=per,proto3" json:"per,omitempty"`
	// 需要的房间数量, room * per = 总共需要的机器人数量
	Room                 int64    `protobuf:"varint,3,opt,name=room,proto3" json:"room,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HireStrangeReq) Reset()         { *m = HireStrangeReq{} }
func (m *HireStrangeReq) String() string { return proto.CompactTextString(m) }
func (*HireStrangeReq) ProtoMessage()    {}
func (*HireStrangeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_65f2a2d7ba3d30b1, []int{0}
}

func (m *HireStrangeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HireStrangeReq.Unmarshal(m, b)
}
func (m *HireStrangeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HireStrangeReq.Marshal(b, m, deterministic)
}
func (m *HireStrangeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HireStrangeReq.Merge(m, src)
}
func (m *HireStrangeReq) XXX_Size() int {
	return xxx_messageInfo_HireStrangeReq.Size(m)
}
func (m *HireStrangeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HireStrangeReq.DiscardUnknown(m)
}

var xxx_messageInfo_HireStrangeReq proto.InternalMessageInfo

func (m *HireStrangeReq) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *HireStrangeReq) GetPer() int64 {
	if m != nil {
		return m.Per
	}
	return 0
}

func (m *HireStrangeReq) GetRoom() int64 {
	if m != nil {
		return m.Room
	}
	return 0
}

type HireStrageResp struct {
	// 机器人的 UserID
	Users                []int64  `protobuf:"varint,1,rep,packed,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HireStrageResp) Reset()         { *m = HireStrageResp{} }
func (m *HireStrageResp) String() string { return proto.CompactTextString(m) }
func (*HireStrageResp) ProtoMessage()    {}
func (*HireStrageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_65f2a2d7ba3d30b1, []int{1}
}

func (m *HireStrageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HireStrageResp.Unmarshal(m, b)
}
func (m *HireStrageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HireStrageResp.Marshal(b, m, deterministic)
}
func (m *HireStrageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HireStrageResp.Merge(m, src)
}
func (m *HireStrageResp) XXX_Size() int {
	return xxx_messageInfo_HireStrageResp.Size(m)
}
func (m *HireStrageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_HireStrageResp.DiscardUnknown(m)
}

var xxx_messageInfo_HireStrageResp proto.InternalMessageInfo

func (m *HireStrageResp) GetUsers() []int64 {
	if m != nil {
		return m.Users
	}
	return nil
}

type MatchCompletedNotify struct {
	// <房间号码, 机器人 UserID>
	Rooms                map[string]*MatchCompletedNotifyValue `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *MatchCompletedNotify) Reset()         { *m = MatchCompletedNotify{} }
func (m *MatchCompletedNotify) String() string { return proto.CompactTextString(m) }
func (*MatchCompletedNotify) ProtoMessage()    {}
func (*MatchCompletedNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_65f2a2d7ba3d30b1, []int{2}
}

func (m *MatchCompletedNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchCompletedNotify.Unmarshal(m, b)
}
func (m *MatchCompletedNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchCompletedNotify.Marshal(b, m, deterministic)
}
func (m *MatchCompletedNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchCompletedNotify.Merge(m, src)
}
func (m *MatchCompletedNotify) XXX_Size() int {
	return xxx_messageInfo_MatchCompletedNotify.Size(m)
}
func (m *MatchCompletedNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchCompletedNotify.DiscardUnknown(m)
}

var xxx_messageInfo_MatchCompletedNotify proto.InternalMessageInfo

func (m *MatchCompletedNotify) GetRooms() map[string]*MatchCompletedNotifyValue {
	if m != nil {
		return m.Rooms
	}
	return nil
}

type MatchCompletedNotifyValue struct {
	Users                []int64  `protobuf:"varint,1,rep,packed,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MatchCompletedNotifyValue) Reset()         { *m = MatchCompletedNotifyValue{} }
func (m *MatchCompletedNotifyValue) String() string { return proto.CompactTextString(m) }
func (*MatchCompletedNotifyValue) ProtoMessage()    {}
func (*MatchCompletedNotifyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_65f2a2d7ba3d30b1, []int{2, 0}
}

func (m *MatchCompletedNotifyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchCompletedNotifyValue.Unmarshal(m, b)
}
func (m *MatchCompletedNotifyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchCompletedNotifyValue.Marshal(b, m, deterministic)
}
func (m *MatchCompletedNotifyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchCompletedNotifyValue.Merge(m, src)
}
func (m *MatchCompletedNotifyValue) XXX_Size() int {
	return xxx_messageInfo_MatchCompletedNotifyValue.Size(m)
}
func (m *MatchCompletedNotifyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchCompletedNotifyValue.DiscardUnknown(m)
}

var xxx_messageInfo_MatchCompletedNotifyValue proto.InternalMessageInfo

func (m *MatchCompletedNotifyValue) GetUsers() []int64 {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*HireStrangeReq)(nil), "pb.strange.HireStrangeReq")
	proto.RegisterType((*HireStrageResp)(nil), "pb.strange.HireStrageResp")
	proto.RegisterType((*MatchCompletedNotify)(nil), "pb.strange.MatchCompletedNotify")
	proto.RegisterMapType((map[string]*MatchCompletedNotifyValue)(nil), "pb.strange.MatchCompletedNotify.RoomsEntry")
	proto.RegisterType((*MatchCompletedNotifyValue)(nil), "pb.strange.MatchCompletedNotify.value")
}

func init() { proto.RegisterFile("strange/strange.proto", fileDescriptor_65f2a2d7ba3d30b1) }

var fileDescriptor_65f2a2d7ba3d30b1 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xc1, 0x4a, 0xeb, 0x40,
	0x14, 0x25, 0xcd, 0xeb, 0x83, 0x77, 0xcb, 0x2b, 0x32, 0x54, 0x09, 0x11, 0xa1, 0x74, 0x51, 0x2b,
	0xe2, 0x04, 0xea, 0x46, 0xc4, 0x8d, 0x4a, 0x51, 0x0a, 0xba, 0x98, 0xee, 0x5c, 0x99, 0xc4, 0xdb,
	0x18, 0x4c, 0x3a, 0xe3, 0xcc, 0xa4, 0x10, 0xff, 0xc7, 0x9f, 0xf2, 0x6b, 0x64, 0x66, 0x52, 0xda,
	0x42, 0xa1, 0xab, 0x9c, 0xcc, 0x9c, 0x73, 0x72, 0xcf, 0xb9, 0x81, 0x43, 0xa5, 0x65, 0xbc, 0xc8,
	0x30, 0x6a, 0x9e, 0x54, 0x48, 0xae, 0x39, 0x01, 0x91, 0xd0, 0xe6, 0x24, 0x3c, 0xce, 0x38, 0xcf,
	0x0a, 0x8c, 0xec, 0x4d, 0x52, 0xcd, 0x23, 0x2c, 0x85, 0xae, 0x1d, 0x71, 0x30, 0x85, 0xee, 0x63,
	0x2e, 0x71, 0xe6, 0xb8, 0x0c, 0x3f, 0x09, 0x81, 0x3f, 0x2a, 0xff, 0xc2, 0xc0, 0xeb, 0x7b, 0x23,
	0x9f, 0x59, 0x4c, 0x0e, 0xc0, 0x17, 0x28, 0x83, 0x96, 0x3d, 0x32, 0xd0, 0xb0, 0x24, 0xe7, 0x65,
	0xe0, 0x3b, 0x96, 0xc1, 0x83, 0xe1, 0xda, 0xcb, 0x58, 0x29, 0x41, 0x7a, 0xd0, 0xae, 0x14, 0x4a,
	0x15, 0x78, 0x7d, 0x7f, 0xe4, 0x33, 0xf7, 0x32, 0xf8, 0xf1, 0xa0, 0xf7, 0x14, 0xeb, 0xf4, 0xfd,
	0x9e, 0x97, 0xa2, 0x40, 0x8d, 0x6f, 0xcf, 0x5c, 0xe7, 0xf3, 0x9a, 0xdc, 0x42, 0xdb, 0x18, 0x39,
	0x7a, 0x67, 0x7c, 0x4e, 0xd7, 0x29, 0xe8, 0x2e, 0x01, 0x65, 0x86, 0x3d, 0x59, 0x68, 0x59, 0x33,
	0xa7, 0x0c, 0x4f, 0xa0, 0xbd, 0x8c, 0x8b, 0x0a, 0x77, 0x7f, 0x3a, 0x7c, 0x05, 0x58, 0x6b, 0x4c,
	0xac, 0x0f, 0xac, 0x6d, 0xd2, 0x7f, 0xcc, 0x40, 0x72, 0xd3, 0xc8, 0x6d, 0xd4, 0xce, 0x78, 0xb8,
	0x77, 0x02, 0xcb, 0x66, 0x4e, 0x74, 0xdd, 0xba, 0xf2, 0xc6, 0xdf, 0x1e, 0x74, 0x9b, 0x36, 0x67,
	0x28, 0x97, 0x79, 0x8a, 0xe4, 0x01, 0xfe, 0x6f, 0x74, 0x2c, 0x15, 0x09, 0x37, 0x6d, 0xb7, 0xeb,
	0x0f, 0x77, 0xde, 0x35, 0x75, 0x4e, 0xa1, 0xbb, 0x3d, 0x04, 0xe9, 0xef, 0x1b, 0x30, 0x3c, 0xa2,
	0x6e, 0xfd, 0x74, 0xb5, 0x7e, 0x3a, 0x31, 0xeb, 0xbf, 0x3b, 0x7b, 0x39, 0xcd, 0x72, 0x5d, 0xc4,
	0x09, 0x4d, 0x79, 0x19, 0x2d, 0x31, 0xd5, 0x5c, 0x56, 0x22, 0x8a, 0x95, 0x42, 0x7d, 0x21, 0x92,
	0x28, 0xe3, 0xab, 0x5f, 0x2a, 0xf9, 0x6b, 0xa5, 0x97, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6f,
	0x42, 0xfc, 0xaf, 0x6c, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StrangeServiceClient is the client API for StrangeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StrangeServiceClient interface {
	// 雇佣新的机器人, 不需要考虑所有机器人都在使用中的情况
	HireStrangers(ctx context.Context, in *HireStrangeReq, opts ...grpc.CallOption) (*HireStrageResp, error)
	MatchCompleted(ctx context.Context, in *MatchCompletedNotify, opts ...grpc.CallOption) (*empty.Empty, error)
}

type strangeServiceClient struct {
	cc *grpc.ClientConn
}

func NewStrangeServiceClient(cc *grpc.ClientConn) StrangeServiceClient {
	return &strangeServiceClient{cc}
}

func (c *strangeServiceClient) HireStrangers(ctx context.Context, in *HireStrangeReq, opts ...grpc.CallOption) (*HireStrageResp, error) {
	out := new(HireStrageResp)
	err := c.cc.Invoke(ctx, "/pb.strange.StrangeService/HireStrangers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strangeServiceClient) MatchCompleted(ctx context.Context, in *MatchCompletedNotify, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.strange.StrangeService/MatchCompleted", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StrangeServiceServer is the server API for StrangeService service.
type StrangeServiceServer interface {
	// 雇佣新的机器人, 不需要考虑所有机器人都在使用中的情况
	HireStrangers(context.Context, *HireStrangeReq) (*HireStrageResp, error)
	MatchCompleted(context.Context, *MatchCompletedNotify) (*empty.Empty, error)
}

func RegisterStrangeServiceServer(s *grpc.Server, srv StrangeServiceServer) {
	s.RegisterService(&_StrangeService_serviceDesc, srv)
}

func _StrangeService_HireStrangers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HireStrangeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrangeServiceServer).HireStrangers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.strange.StrangeService/HireStrangers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrangeServiceServer).HireStrangers(ctx, req.(*HireStrangeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrangeService_MatchCompleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchCompletedNotify)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrangeServiceServer).MatchCompleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.strange.StrangeService/MatchCompleted",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrangeServiceServer).MatchCompleted(ctx, req.(*MatchCompletedNotify))
	}
	return interceptor(ctx, in, info, handler)
}

var _StrangeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.strange.StrangeService",
	HandlerType: (*StrangeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HireStrangers",
			Handler:    _StrangeService_HireStrangers_Handler,
		},
		{
			MethodName: "MatchCompleted",
			Handler:    _StrangeService_MatchCompleted_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "strange/strange.proto",
}
