// Code generated by protoc-gen-go. DO NOT EDIT.
// source: im/im-message.proto

package im

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	consts "gitlab.com/vectorup/asset-pb/go/consts"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IMMessageType_Enum int32

const (
	IMMessageType_UNKNOWN IMMessageType_Enum = 0
	// 点赞
	IMMessageType_THUMB_UP IMMessageType_Enum = 1
	// 评论
	IMMessageType_COMMENT IMMessageType_Enum = 2
	// 加好友请求
	IMMessageType_FRIEND_REQUEST IMMessageType_Enum = 3
	// 加好友回应
	// NOTE(QuantumGhost): 这个现在前端自己发的，后端暂时不需要发送这个事件
	IMMessageType_FRIEND_REQUEST_RESPONSE IMMessageType_Enum = 4
	// 发财富圈
	IMMessageType_MOMENT_POST IMMessageType_Enum = 5
	// 公告，包括新版本通知
	IMMessageType_ANNOUNCEMENT IMMessageType_Enum = 7
	// 游戏邀请
	IMMessageType_GAME_INVITATION IMMessageType_Enum = 8
	// 好友关系发生变化
	IMMessageType_FRIEND_RELATIONSHIP_CHANGE IMMessageType_Enum = 9
	// 群邀请
	IMMessageType_GROUP_INVITATION IMMessageType_Enum = 10
	// 加群申请
	IMMessageType_GROUP_JOIN_APPLY IMMessageType_Enum = 11
	// 加群申请结果
	IMMessageType_GROUP_JOIN_RESULT IMMessageType_Enum = 12
	// 交易通知消息
	IMMessageType_TRANSACTION_NOTIFICATION IMMessageType_Enum = 13
	IMMessageType_LINK_MESSAGE             IMMessageType_Enum = 14
	// 群消息点赞数量变化消息
	IMMessageType_GROUP_MESSAGE_THUMB_UP IMMessageType_Enum = 15
)

var IMMessageType_Enum_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "THUMB_UP",
	2:  "COMMENT",
	3:  "FRIEND_REQUEST",
	4:  "FRIEND_REQUEST_RESPONSE",
	5:  "MOMENT_POST",
	7:  "ANNOUNCEMENT",
	8:  "GAME_INVITATION",
	9:  "FRIEND_RELATIONSHIP_CHANGE",
	10: "GROUP_INVITATION",
	11: "GROUP_JOIN_APPLY",
	12: "GROUP_JOIN_RESULT",
	13: "TRANSACTION_NOTIFICATION",
	14: "LINK_MESSAGE",
	15: "GROUP_MESSAGE_THUMB_UP",
}

var IMMessageType_Enum_value = map[string]int32{
	"UNKNOWN":                    0,
	"THUMB_UP":                   1,
	"COMMENT":                    2,
	"FRIEND_REQUEST":             3,
	"FRIEND_REQUEST_RESPONSE":    4,
	"MOMENT_POST":                5,
	"ANNOUNCEMENT":               7,
	"GAME_INVITATION":            8,
	"FRIEND_RELATIONSHIP_CHANGE": 9,
	"GROUP_INVITATION":           10,
	"GROUP_JOIN_APPLY":           11,
	"GROUP_JOIN_RESULT":          12,
	"TRANSACTION_NOTIFICATION":   13,
	"LINK_MESSAGE":               14,
	"GROUP_MESSAGE_THUMB_UP":     15,
}

func (x IMMessageType_Enum) String() string {
	return proto.EnumName(IMMessageType_Enum_name, int32(x))
}

func (IMMessageType_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a75bf3faa657f674, []int{1, 0}
}

type FriendRelationshipChangeMsg_ChangeType int32

const (
	FriendRelationshipChangeMsg_UNKNOWN FriendRelationshipChangeMsg_ChangeType = 0
	FriendRelationshipChangeMsg_ADD     FriendRelationshipChangeMsg_ChangeType = 1
	FriendRelationshipChangeMsg_DELETE  FriendRelationshipChangeMsg_ChangeType = 2
)

var FriendRelationshipChangeMsg_ChangeType_name = map[int32]string{
	0: "UNKNOWN",
	1: "ADD",
	2: "DELETE",
}

var FriendRelationshipChangeMsg_ChangeType_value = map[string]int32{
	"UNKNOWN": 0,
	"ADD":     1,
	"DELETE":  2,
}

func (x FriendRelationshipChangeMsg_ChangeType) String() string {
	return proto.EnumName(FriendRelationshipChangeMsg_ChangeType_name, int32(x))
}

func (FriendRelationshipChangeMsg_ChangeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a75bf3faa657f674, []int{11, 0}
}

type TransactionNotificationType_Enum int32

const (
	TransactionNotificationType_UNKNOWN TransactionNotificationType_Enum = 0
	// 收款
	TransactionNotificationType_RECEIVE TransactionNotificationType_Enum = 1
	// 支付
	TransactionNotificationType_PAY TransactionNotificationType_Enum = 2
	// 退款
	TransactionNotificationType_REFUND TransactionNotificationType_Enum = 3
)

var TransactionNotificationType_Enum_name = map[int32]string{
	0: "UNKNOWN",
	1: "RECEIVE",
	2: "PAY",
	3: "REFUND",
}

var TransactionNotificationType_Enum_value = map[string]int32{
	"UNKNOWN": 0,
	"RECEIVE": 1,
	"PAY":     2,
	"REFUND":  3,
}

func (x TransactionNotificationType_Enum) String() string {
	return proto.EnumName(TransactionNotificationType_Enum_name, int32(x))
}

func (TransactionNotificationType_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a75bf3faa657f674, []int{16, 0}
}

type IMMessage struct {
	// 消息体的类型
	Type IMMessageType_Enum `protobuf:"varint,1,opt,name=type,proto3,enum=pb.im.IMMessageType_Enum" json:"type,omitempty"`
	// NOTE(QuantumGhost): 这里留几个 slot 来后面加 header 之类的东西
	// 消息具体的 Payload，这里直接用 Any 类型，具体的内容跟 type 对应
	Content              *any.Any `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IMMessage) Reset()         { *m = IMMessage{} }
func (m *IMMessage) String() string { return proto.CompactTextString(m) }
func (*IMMessage) ProtoMessage()    {}
func (*IMMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a75bf3faa657f674, []int{0}
}

func (m *IMMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMMessage.Unmarshal(m, b)
}
func (m *IMMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMMessage.Marshal(b, m, deterministic)
}
func (m *IMMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMMessage.Merge(m, src)
}
func (m *IMMessage) XXX_Size() int {
	return xxx_messageInfo_IMMessage.Size(m)
}
func (m *IMMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_IMMessage.DiscardUnknown(m)
}

var xxx_messageInfo_IMMessage proto.InternalMessageInfo

func (m *IMMessage) GetType() IMMessageType_Enum {
	if m != nil {
		return m.Type
	}
	return IMMessageType_UNKNOWN
}

func (m *IMMessage) GetContent() *any.Any {
	if m != nil {
		return m.Content
	}
	return nil
}

// 这里定义通过 im 发送的自定义消息的类型
// NOTE(QuantumGhost): 每个 Enum 类型都应该有对应的消息，对应的消息应该叫 `$TYPE$Msg`
type IMMessageType struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IMMessageType) Reset()         { *m = IMMessageType{} }
func (m *IMMessageType) String() string { return proto.CompactTextString(m) }
func (*IMMessageType) ProtoMessage()    {}
func (*IMMessageType) Descriptor() ([]byte, []int) {
	return fileDescriptor_a75bf3faa657f674, []int{1}
}

func (m *IMMessageType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMMessageType.Unmarshal(m, b)
}
func (m *IMMessageType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMMessageType.Marshal(b, m, deterministic)
}
func (m *IMMessageType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMMessageType.Merge(m, src)
}
func (m *IMMessageType) XXX_Size() int {
	return xxx_messageInfo_IMMessageType.Size(m)
}
func (m *IMMessageType) XXX_DiscardUnknown() {
	xxx_messageInfo_IMMessageType.DiscardUnknown(m)
}

var xxx_messageInfo_IMMessageType proto.InternalMessageInfo

// 通用的用户信息字段
type UserInfo struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar               string   `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a75bf3faa657f674, []int{2}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

// 点赞 / 评论的 target 的摘要
// 如果有 imageUrls 优先显示图片，否则显示 text
type TargetSummary struct {
	ObjectType consts.ObjectType_Enum `protobuf:"varint,1,opt,name=objectType,proto3,enum=pb.consts.ObjectType_Enum" json:"objectType,omitempty"`
	ObjectId   string                 `protobuf:"bytes,2,opt,name=objectId,proto3" json:"objectId,omitempty"`
	// 要显示的文字
	Text string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	// 要显示的图片
	ImageUrls            []string `protobuf:"bytes,4,rep,name=imageUrls,proto3" json:"imageUrls,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TargetSummary) Reset()         { *m = TargetSummary{} }
func (m *TargetSummary) String() string { return proto.CompactTextString(m) }
func (*TargetSummary) ProtoMessage()    {}
func (*TargetSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_a75bf3faa657f674, []int{3}
}

func (m *TargetSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TargetSummary.Unmarshal(m, b)
}
func (m *TargetSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TargetSummary.Marshal(b, m, deterministic)
}
func (m *TargetSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TargetSummary.Merge(m, src)
}
func (m *TargetSummary) XXX_Size() int {
	return xxx_messageInfo_TargetSummary.Size(m)
}
func (m *TargetSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_TargetSummary.DiscardUnknown(m)
}

var xxx_messageInfo_TargetSummary proto.InternalMessageInfo

func (m *TargetSummary) GetObjectType() consts.ObjectType_Enum {
	if m != nil {
		return m.ObjectType
	}
	return consts.ObjectType_UNKNOWN
}

func (m *TargetSummary) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

func (m *TargetSummary) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *TargetSummary) GetImageUrls() []string {
	if m != nil {
		return m.ImageUrls
	}
	return nil
}

// THUMB_UP = 1;
type ThumpUpMsg struct {
	Sender               *UserInfo              `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	CreatedAt            *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	ObjectType           consts.ObjectType_Enum `protobuf:"varint,3,opt,name=objectType,proto3,enum=pb.consts.ObjectType_Enum" json:"objectType,omitempty"`
	ObjectId             string                 `protobuf:"bytes,4,opt,name=objectId,proto3" json:"objectId,omitempty"`
	Summary              *TargetSummary         `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ThumpUpMsg) Reset()         { *m = ThumpUpMsg{} }
func (m *ThumpUpMsg) String() string { return proto.CompactTextString(m) }
func (*ThumpUpMsg) ProtoMessage()    {}
func (*ThumpUpMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_a75bf3faa657f674, []int{4}
}

func (m *ThumpUpMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThumpUpMsg.Unmarshal(m, b)
}
func (m *ThumpUpMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThumpUpMsg.Marshal(b, m, deterministic)
}
func (m *ThumpUpMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThumpUpMsg.Merge(m, src)
}
func (m *ThumpUpMsg) XXX_Size() int {
	return xxx_messageInfo_ThumpUpMsg.Size(m)
}
func (m *ThumpUpMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ThumpUpMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ThumpUpMsg proto.InternalMessageInfo

func (m *ThumpUpMsg) GetSender() *UserInfo {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *ThumpUpMsg) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *ThumpUpMsg) GetObjectType() consts.ObjectType_Enum {
	if m != nil {
		return m.ObjectType
	}
	return consts.ObjectType_UNKNOWN
}

func (m *ThumpUpMsg) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

func (m *ThumpUpMsg) GetSummary() *TargetSummary {
	if m != nil {
		return m.Summary
	}
	return nil
}

// COMMENT = 2;
type CommentMsg struct {
	Sender     *UserInfo              `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	CreatedAt  *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Content    string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ObjectType consts.ObjectType_Enum `protobuf:"varint,4,opt,name=objectType,proto3,enum=pb.consts.ObjectType_Enum" json:"objectType,omitempty"`
	ObjectId   string                 `protobuf:"bytes,5,opt,name=objectId,proto3" json:"objectId,omitempty"`
	Summary    *TargetSummary         `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
	// 评论支付的费用,  "" 或 0 表示不用付费
	Fee string `protobuf:"bytes,7,opt,name=fee,proto3" json:"fee,omitempty"`
	// 如果是回复评论, 这里表示被回复的评论 ID
	ReplyTo              string   `protobuf:"bytes,8,opt,name=replyTo,proto3" json:"replyTo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentMsg) Reset()         { *m = CommentMsg{} }
func (m *CommentMsg) String() string { return proto.CompactTextString(m) }
func (*CommentMsg) ProtoMessage()    {}
func (*CommentMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_a75bf3faa657f674, []int{5}
}

func (m *CommentMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentMsg.Unmarshal(m, b)
}
func (m *CommentMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentMsg.Marshal(b, m, deterministic)
}
func (m *CommentMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentMsg.Merge(m, src)
}
func (m *CommentMsg) XXX_Size() int {
	return xxx_messageInfo_CommentMsg.Size(m)
}
func (m *CommentMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentMsg.DiscardUnknown(m)
}

var xxx_messageInfo_CommentMsg proto.InternalMessageInfo

func (m *CommentMsg) GetSender() *UserInfo {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *CommentMsg) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *CommentMsg) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CommentMsg) GetObjectType() consts.ObjectType_Enum {
	if m != nil {
		return m.ObjectType
	}
	return consts.ObjectType_UNKNOWN
}

func (m *CommentMsg) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

func (m *CommentMsg) GetSummary() *TargetSummary {
	if m != nil {
		return m.Summary
	}
	return nil
}

func (m *CommentMsg) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

func (m *CommentMsg) GetReplyTo() string {
	if m != nil {
		return m.ReplyTo
	}
	return ""
}

// FRIEND_REQUEST = 3;
type FriendRequestMsg struct {
	// 发送者信息
	Sender *UserInfo `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// 好友申请文本
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendRequestMsg) Reset()         { *m = FriendRequestMsg{} }
func (m *FriendRequestMsg) String() string { return proto.CompactTextString(m) }
func (*FriendRequestMsg) ProtoMessage()    {}
func (*FriendRequestMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_a75bf3faa657f674, []int{6}
}

func (m *FriendRequestMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendRequestMsg.Unmarshal(m, b)
}
func (m *FriendRequestMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendRequestMsg.Marshal(b, m, deterministic)
}
func (m *FriendRequestMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendRequestMsg.Merge(m, src)
}
func (m *FriendRequestMsg) XXX_Size() int {
	return xxx_messageInfo_FriendRequestMsg.Size(m)
}
func (m *FriendRequestMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendRequestMsg.DiscardUnknown(m)
}

var xxx_messageInfo_FriendRequestMsg proto.InternalMessageInfo

func (m *FriendRequestMsg) GetSender() *UserInfo {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *FriendRequestMsg) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

// FRIEND_REQUEST_RESPONSE = 4;
type FriendRequestResponseMsg struct {
	Sender *UserInfo `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// NOTE(QuantumGhost): 目前业务上没有拒绝逻辑，因此如果收到消息就一定是通过了
	Accepted             bool     `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendRequestResponseMsg) Reset()         { *m = FriendRequestResponseMsg{} }
func (m *FriendRequestResponseMsg) String() string { return proto.CompactTextString(m) }
func (*FriendRequestResponseMsg) ProtoMessage()    {}
func (*FriendRequestResponseMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_a75bf3faa657f674, []int{7}
}

func (m *FriendRequestResponseMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendRequestResponseMsg.Unmarshal(m, b)
}
func (m *FriendRequestResponseMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendRequestResponseMsg.Marshal(b, m, deterministic)
}
func (m *FriendRequestResponseMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendRequestResponseMsg.Merge(m, src)
}
func (m *FriendRequestResponseMsg) XXX_Size() int {
	return xxx_messageInfo_FriendRequestResponseMsg.Size(m)
}
func (m *FriendRequestResponseMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendRequestResponseMsg.DiscardUnknown(m)
}

var xxx_messageInfo_FriendRequestResponseMsg proto.InternalMessageInfo

func (m *FriendRequestResponseMsg) GetSender() *UserInfo {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *FriendRequestResponseMsg) GetAccepted() bool {
	if m != nil {
		return m.Accepted
	}
	return false
}

// MOMENT_POST = 5;
// TODO(QuantumGhost): 这里要看设计稿上的通知样式来决定具体要推什么内容
type MomentPostMsg struct {
	Sender               *UserInfo `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MomentPostMsg) Reset()         { *m = MomentPostMsg{} }
func (m *MomentPostMsg) String() string { return proto.CompactTextString(m) }
func (*MomentPostMsg) ProtoMessage()    {}
func (*MomentPostMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_a75bf3faa657f674, []int{8}
}

func (m *MomentPostMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MomentPostMsg.Unmarshal(m, b)
}
func (m *MomentPostMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MomentPostMsg.Marshal(b, m, deterministic)
}
func (m *MomentPostMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MomentPostMsg.Merge(m, src)
}
func (m *MomentPostMsg) XXX_Size() int {
	return xxx_messageInfo_MomentPostMsg.Size(m)
}
func (m *MomentPostMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_MomentPostMsg.DiscardUnknown(m)
}

var xxx_messageInfo_MomentPostMsg proto.InternalMessageInfo

func (m *MomentPostMsg) GetSender() *UserInfo {
	if m != nil {
		return m.Sender
	}
	return nil
}

// ANNOUNCEMENT = 7;
type AnnouncementMsg struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnnouncementMsg) Reset()         { *m = AnnouncementMsg{} }
func (m *AnnouncementMsg) String() string { return proto.CompactTextString(m) }
func (*AnnouncementMsg) ProtoMessage()    {}
func (*AnnouncementMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_a75bf3faa657f674, []int{9}
}

func (m *AnnouncementMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnnouncementMsg.Unmarshal(m, b)
}
func (m *AnnouncementMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnnouncementMsg.Marshal(b, m, deterministic)
}
func (m *AnnouncementMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnnouncementMsg.Merge(m, src)
}
func (m *AnnouncementMsg) XXX_Size() int {
	return xxx_messageInfo_AnnouncementMsg.Size(m)
}
func (m *AnnouncementMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_AnnouncementMsg.DiscardUnknown(m)
}

var xxx_messageInfo_AnnouncementMsg proto.InternalMessageInfo

func (m *AnnouncementMsg) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// GAME_INVITATION = 8;
type GameInvitationMsg struct {
	Sender               *UserInfo `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	RoomId               string    `protobuf:"bytes,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	AssetScore           int32     `protobuf:"varint,3,opt,name=assetScore,proto3" json:"assetScore,omitempty"`
	AssetLevel           string    `protobuf:"bytes,4,opt,name=assetLevel,proto3" json:"assetLevel,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GameInvitationMsg) Reset()         { *m = GameInvitationMsg{} }
func (m *GameInvitationMsg) String() string { return proto.CompactTextString(m) }
func (*GameInvitationMsg) ProtoMessage()    {}
func (*GameInvitationMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_a75bf3faa657f674, []int{10}
}

func (m *GameInvitationMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameInvitationMsg.Unmarshal(m, b)
}
func (m *GameInvitationMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameInvitationMsg.Marshal(b, m, deterministic)
}
func (m *GameInvitationMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameInvitationMsg.Merge(m, src)
}
func (m *GameInvitationMsg) XXX_Size() int {
	return xxx_messageInfo_GameInvitationMsg.Size(m)
}
func (m *GameInvitationMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_GameInvitationMsg.DiscardUnknown(m)
}

var xxx_messageInfo_GameInvitationMsg proto.InternalMessageInfo

func (m *GameInvitationMsg) GetSender() *UserInfo {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *GameInvitationMsg) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *GameInvitationMsg) GetAssetScore() int32 {
	if m != nil {
		return m.AssetScore
	}
	return 0
}

func (m *GameInvitationMsg) GetAssetLevel() string {
	if m != nil {
		return m.AssetLevel
	}
	return ""
}

// 好友关系发生变化
// FRIEND_RELATIONSHIP_CHANGE = 9;
type FriendRelationshipChangeMsg struct {
	Type FriendRelationshipChangeMsg_ChangeType `protobuf:"varint,1,opt,name=type,proto3,enum=pb.im.FriendRelationshipChangeMsg_ChangeType" json:"type,omitempty"`
	// 变化的好友的 user_id
	// 如果是添加了好友，那么这个 id 就是新好友的 id
	// 如果是删除了好友，那么这个 id 就是被删除的好友的 id
	// 举个栗子：如果 A 通过了 B 的好友申请，那么发给 A 的 FriendRelationshipChangeMsg 里面的
	// userId 就是 B 的 id，同时，发给 B 的 FriendRelationshipChangeMsg 里面的 userId 是 A 的 id
	// 删除的情况类似，双方都会收到包含对方 userId 的 msg
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendRelationshipChangeMsg) Reset()         { *m = FriendRelationshipChangeMsg{} }
func (m *FriendRelationshipChangeMsg) String() string { return proto.CompactTextString(m) }
func (*FriendRelationshipChangeMsg) ProtoMessage()    {}
func (*FriendRelationshipChangeMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_a75bf3faa657f674, []int{11}
}

func (m *FriendRelationshipChangeMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendRelationshipChangeMsg.Unmarshal(m, b)
}
func (m *FriendRelationshipChangeMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendRelationshipChangeMsg.Marshal(b, m, deterministic)
}
func (m *FriendRelationshipChangeMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendRelationshipChangeMsg.Merge(m, src)
}
func (m *FriendRelationshipChangeMsg) XXX_Size() int {
	return xxx_messageInfo_FriendRelationshipChangeMsg.Size(m)
}
func (m *FriendRelationshipChangeMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendRelationshipChangeMsg.DiscardUnknown(m)
}

var xxx_messageInfo_FriendRelationshipChangeMsg proto.InternalMessageInfo

func (m *FriendRelationshipChangeMsg) GetType() FriendRelationshipChangeMsg_ChangeType {
	if m != nil {
		return m.Type
	}
	return FriendRelationshipChangeMsg_UNKNOWN
}

func (m *FriendRelationshipChangeMsg) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

// 群邀请
// GROUP_INVITATION = 10;
type GroupInvitationMsg struct {
	// 群名称
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 群成员数量
	MemberNum int32 `protobuf:"varint,2,opt,name=memberNum,proto3" json:"memberNum,omitempty"`
	// 群阶层字符（A7.9）
	Ranking string `protobuf:"bytes,3,opt,name=ranking,proto3" json:"ranking,omitempty"`
	// 群 id
	GroupId string `protobuf:"bytes,4,opt,name=groupId,proto3" json:"groupId,omitempty"`
	// 群头像地址
	GroupAvatarUrl       string   `protobuf:"bytes,5,opt,name=groupAvatarUrl,proto3" json:"groupAvatarUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupInvitationMsg) Reset()         { *m = GroupInvitationMsg{} }
func (m *GroupInvitationMsg) String() string { return proto.CompactTextString(m) }
func (*GroupInvitationMsg) ProtoMessage()    {}
func (*GroupInvitationMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_a75bf3faa657f674, []int{12}
}

func (m *GroupInvitationMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupInvitationMsg.Unmarshal(m, b)
}
func (m *GroupInvitationMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupInvitationMsg.Marshal(b, m, deterministic)
}
func (m *GroupInvitationMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupInvitationMsg.Merge(m, src)
}
func (m *GroupInvitationMsg) XXX_Size() int {
	return xxx_messageInfo_GroupInvitationMsg.Size(m)
}
func (m *GroupInvitationMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupInvitationMsg.DiscardUnknown(m)
}

var xxx_messageInfo_GroupInvitationMsg proto.InternalMessageInfo

func (m *GroupInvitationMsg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GroupInvitationMsg) GetMemberNum() int32 {
	if m != nil {
		return m.MemberNum
	}
	return 0
}

func (m *GroupInvitationMsg) GetRanking() string {
	if m != nil {
		return m.Ranking
	}
	return ""
}

func (m *GroupInvitationMsg) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *GroupInvitationMsg) GetGroupAvatarUrl() string {
	if m != nil {
		return m.GroupAvatarUrl
	}
	return ""
}

type GroupJoinApplyMsg struct {
	// 申请人信息
	Applier *UserInfo `protobuf:"bytes,1,opt,name=applier,proto3" json:"applier,omitempty"`
	// 群信息
	GroupInfo *GroupInfo `protobuf:"bytes,2,opt,name=groupInfo,proto3" json:"groupInfo,omitempty"`
	// 邀请者昵称
	InvitorNickName string `protobuf:"bytes,3,opt,name=invitorNickName,proto3" json:"invitorNickName,omitempty"`
	// 是否进行了支付
	HasPaid bool `protobuf:"varint,4,opt,name=hasPaid,proto3" json:"hasPaid,omitempty"`
	// 支付的 acc 金额
	AccAmountString string `protobuf:"bytes,5,opt,name=accAmountString,proto3" json:"accAmountString,omitempty"`
	// 群申请 id，给群主获取申请状态用
	ApplicationId        string   `protobuf:"bytes,6,opt,name=applicationId,proto3" json:"applicationId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupJoinApplyMsg) Reset()         { *m = GroupJoinApplyMsg{} }
func (m *GroupJoinApplyMsg) String() string { return proto.CompactTextString(m) }
func (*GroupJoinApplyMsg) ProtoMessage()    {}
func (*GroupJoinApplyMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_a75bf3faa657f674, []int{13}
}

func (m *GroupJoinApplyMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupJoinApplyMsg.Unmarshal(m, b)
}
func (m *GroupJoinApplyMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupJoinApplyMsg.Marshal(b, m, deterministic)
}
func (m *GroupJoinApplyMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupJoinApplyMsg.Merge(m, src)
}
func (m *GroupJoinApplyMsg) XXX_Size() int {
	return xxx_messageInfo_GroupJoinApplyMsg.Size(m)
}
func (m *GroupJoinApplyMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupJoinApplyMsg.DiscardUnknown(m)
}

var xxx_messageInfo_GroupJoinApplyMsg proto.InternalMessageInfo

func (m *GroupJoinApplyMsg) GetApplier() *UserInfo {
	if m != nil {
		return m.Applier
	}
	return nil
}

func (m *GroupJoinApplyMsg) GetGroupInfo() *GroupInfo {
	if m != nil {
		return m.GroupInfo
	}
	return nil
}

func (m *GroupJoinApplyMsg) GetInvitorNickName() string {
	if m != nil {
		return m.InvitorNickName
	}
	return ""
}

func (m *GroupJoinApplyMsg) GetHasPaid() bool {
	if m != nil {
		return m.HasPaid
	}
	return false
}

func (m *GroupJoinApplyMsg) GetAccAmountString() string {
	if m != nil {
		return m.AccAmountString
	}
	return ""
}

func (m *GroupJoinApplyMsg) GetApplicationId() string {
	if m != nil {
		return m.ApplicationId
	}
	return ""
}

type GroupInfo struct {
	// 群 id
	GroupId string `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	// 群名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 群头像
	FaceUrl              string   `protobuf:"bytes,3,opt,name=faceUrl,proto3" json:"faceUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupInfo) Reset()         { *m = GroupInfo{} }
func (m *GroupInfo) String() string { return proto.CompactTextString(m) }
func (*GroupInfo) ProtoMessage()    {}
func (*GroupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a75bf3faa657f674, []int{14}
}

func (m *GroupInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupInfo.Unmarshal(m, b)
}
func (m *GroupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupInfo.Marshal(b, m, deterministic)
}
func (m *GroupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupInfo.Merge(m, src)
}
func (m *GroupInfo) XXX_Size() int {
	return xxx_messageInfo_GroupInfo.Size(m)
}
func (m *GroupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GroupInfo proto.InternalMessageInfo

func (m *GroupInfo) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *GroupInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GroupInfo) GetFaceUrl() string {
	if m != nil {
		return m.FaceUrl
	}
	return ""
}

type GroupJoinResultMsg struct {
	// 群组概要
	GroupInfo *GroupInfo `protobuf:"bytes,1,opt,name=groupInfo,proto3" json:"groupInfo,omitempty"`
	// 申请是否被接受
	Accepted bool `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// 是否进行了支付
	HasPaid bool `protobuf:"varint,3,opt,name=hasPaid,proto3" json:"hasPaid,omitempty"`
	// 支付的 acc 金额
	AccAmountString      string   `protobuf:"bytes,4,opt,name=accAmountString,proto3" json:"accAmountString,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupJoinResultMsg) Reset()         { *m = GroupJoinResultMsg{} }
func (m *GroupJoinResultMsg) String() string { return proto.CompactTextString(m) }
func (*GroupJoinResultMsg) ProtoMessage()    {}
func (*GroupJoinResultMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_a75bf3faa657f674, []int{15}
}

func (m *GroupJoinResultMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupJoinResultMsg.Unmarshal(m, b)
}
func (m *GroupJoinResultMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupJoinResultMsg.Marshal(b, m, deterministic)
}
func (m *GroupJoinResultMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupJoinResultMsg.Merge(m, src)
}
func (m *GroupJoinResultMsg) XXX_Size() int {
	return xxx_messageInfo_GroupJoinResultMsg.Size(m)
}
func (m *GroupJoinResultMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupJoinResultMsg.DiscardUnknown(m)
}

var xxx_messageInfo_GroupJoinResultMsg proto.InternalMessageInfo

func (m *GroupJoinResultMsg) GetGroupInfo() *GroupInfo {
	if m != nil {
		return m.GroupInfo
	}
	return nil
}

func (m *GroupJoinResultMsg) GetAccepted() bool {
	if m != nil {
		return m.Accepted
	}
	return false
}

func (m *GroupJoinResultMsg) GetHasPaid() bool {
	if m != nil {
		return m.HasPaid
	}
	return false
}

func (m *GroupJoinResultMsg) GetAccAmountString() string {
	if m != nil {
		return m.AccAmountString
	}
	return ""
}

// 交易通知类型
type TransactionNotificationType struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionNotificationType) Reset()         { *m = TransactionNotificationType{} }
func (m *TransactionNotificationType) String() string { return proto.CompactTextString(m) }
func (*TransactionNotificationType) ProtoMessage()    {}
func (*TransactionNotificationType) Descriptor() ([]byte, []int) {
	return fileDescriptor_a75bf3faa657f674, []int{16}
}

func (m *TransactionNotificationType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionNotificationType.Unmarshal(m, b)
}
func (m *TransactionNotificationType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionNotificationType.Marshal(b, m, deterministic)
}
func (m *TransactionNotificationType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionNotificationType.Merge(m, src)
}
func (m *TransactionNotificationType) XXX_Size() int {
	return xxx_messageInfo_TransactionNotificationType.Size(m)
}
func (m *TransactionNotificationType) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionNotificationType.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionNotificationType proto.InternalMessageInfo

// 交易通知消息
type TransactionNotificationMsg struct {
	// 收款人信息
	User *UserInfo `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// 交易备注
	Comment string `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	// 交易金额
	Amount string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// 交易的 id
	TradeId string `protobuf:"bytes,4,opt,name=tradeId,proto3" json:"tradeId,omitempty"`
	// 交易通知类型
	Type                 TransactionNotificationType_Enum `protobuf:"varint,5,opt,name=type,proto3,enum=pb.im.TransactionNotificationType_Enum" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *TransactionNotificationMsg) Reset()         { *m = TransactionNotificationMsg{} }
func (m *TransactionNotificationMsg) String() string { return proto.CompactTextString(m) }
func (*TransactionNotificationMsg) ProtoMessage()    {}
func (*TransactionNotificationMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_a75bf3faa657f674, []int{17}
}

func (m *TransactionNotificationMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionNotificationMsg.Unmarshal(m, b)
}
func (m *TransactionNotificationMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionNotificationMsg.Marshal(b, m, deterministic)
}
func (m *TransactionNotificationMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionNotificationMsg.Merge(m, src)
}
func (m *TransactionNotificationMsg) XXX_Size() int {
	return xxx_messageInfo_TransactionNotificationMsg.Size(m)
}
func (m *TransactionNotificationMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionNotificationMsg.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionNotificationMsg proto.InternalMessageInfo

func (m *TransactionNotificationMsg) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *TransactionNotificationMsg) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *TransactionNotificationMsg) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *TransactionNotificationMsg) GetTradeId() string {
	if m != nil {
		return m.TradeId
	}
	return ""
}

func (m *TransactionNotificationMsg) GetType() TransactionNotificationType_Enum {
	if m != nil {
		return m.Type
	}
	return TransactionNotificationType_UNKNOWN
}

type LinkMsg struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	FaviconUrl           string   `protobuf:"bytes,4,opt,name=faviconUrl,proto3" json:"faviconUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LinkMsg) Reset()         { *m = LinkMsg{} }
func (m *LinkMsg) String() string { return proto.CompactTextString(m) }
func (*LinkMsg) ProtoMessage()    {}
func (*LinkMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_a75bf3faa657f674, []int{18}
}

func (m *LinkMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkMsg.Unmarshal(m, b)
}
func (m *LinkMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkMsg.Marshal(b, m, deterministic)
}
func (m *LinkMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkMsg.Merge(m, src)
}
func (m *LinkMsg) XXX_Size() int {
	return xxx_messageInfo_LinkMsg.Size(m)
}
func (m *LinkMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkMsg.DiscardUnknown(m)
}

var xxx_messageInfo_LinkMsg proto.InternalMessageInfo

func (m *LinkMsg) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *LinkMsg) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *LinkMsg) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *LinkMsg) GetFaviconUrl() string {
	if m != nil {
		return m.FaviconUrl
	}
	return ""
}

// 群消息点赞数量变化消息
type GroupMessageThumbUpMsg struct {
	GroupID string `protobuf:"bytes,1,opt,name=groupID,proto3" json:"groupID,omitempty"`
	// cenarius 服务端生成的消息 ID
	MsgID string `protobuf:"bytes,2,opt,name=msgID,proto3" json:"msgID,omitempty"`
	// 直接推送群消息当前点赞数量
	Count                int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupMessageThumbUpMsg) Reset()         { *m = GroupMessageThumbUpMsg{} }
func (m *GroupMessageThumbUpMsg) String() string { return proto.CompactTextString(m) }
func (*GroupMessageThumbUpMsg) ProtoMessage()    {}
func (*GroupMessageThumbUpMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_a75bf3faa657f674, []int{19}
}

func (m *GroupMessageThumbUpMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupMessageThumbUpMsg.Unmarshal(m, b)
}
func (m *GroupMessageThumbUpMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupMessageThumbUpMsg.Marshal(b, m, deterministic)
}
func (m *GroupMessageThumbUpMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupMessageThumbUpMsg.Merge(m, src)
}
func (m *GroupMessageThumbUpMsg) XXX_Size() int {
	return xxx_messageInfo_GroupMessageThumbUpMsg.Size(m)
}
func (m *GroupMessageThumbUpMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupMessageThumbUpMsg.DiscardUnknown(m)
}

var xxx_messageInfo_GroupMessageThumbUpMsg proto.InternalMessageInfo

func (m *GroupMessageThumbUpMsg) GetGroupID() string {
	if m != nil {
		return m.GroupID
	}
	return ""
}

func (m *GroupMessageThumbUpMsg) GetMsgID() string {
	if m != nil {
		return m.MsgID
	}
	return ""
}

func (m *GroupMessageThumbUpMsg) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterEnum("pb.im.IMMessageType_Enum", IMMessageType_Enum_name, IMMessageType_Enum_value)
	proto.RegisterEnum("pb.im.FriendRelationshipChangeMsg_ChangeType", FriendRelationshipChangeMsg_ChangeType_name, FriendRelationshipChangeMsg_ChangeType_value)
	proto.RegisterEnum("pb.im.TransactionNotificationType_Enum", TransactionNotificationType_Enum_name, TransactionNotificationType_Enum_value)
	proto.RegisterType((*IMMessage)(nil), "pb.im.IMMessage")
	proto.RegisterType((*IMMessageType)(nil), "pb.im.IMMessageType")
	proto.RegisterType((*UserInfo)(nil), "pb.im.UserInfo")
	proto.RegisterType((*TargetSummary)(nil), "pb.im.TargetSummary")
	proto.RegisterType((*ThumpUpMsg)(nil), "pb.im.ThumpUpMsg")
	proto.RegisterType((*CommentMsg)(nil), "pb.im.CommentMsg")
	proto.RegisterType((*FriendRequestMsg)(nil), "pb.im.FriendRequestMsg")
	proto.RegisterType((*FriendRequestResponseMsg)(nil), "pb.im.FriendRequestResponseMsg")
	proto.RegisterType((*MomentPostMsg)(nil), "pb.im.MomentPostMsg")
	proto.RegisterType((*AnnouncementMsg)(nil), "pb.im.AnnouncementMsg")
	proto.RegisterType((*GameInvitationMsg)(nil), "pb.im.GameInvitationMsg")
	proto.RegisterType((*FriendRelationshipChangeMsg)(nil), "pb.im.FriendRelationshipChangeMsg")
	proto.RegisterType((*GroupInvitationMsg)(nil), "pb.im.GroupInvitationMsg")
	proto.RegisterType((*GroupJoinApplyMsg)(nil), "pb.im.GroupJoinApplyMsg")
	proto.RegisterType((*GroupInfo)(nil), "pb.im.GroupInfo")
	proto.RegisterType((*GroupJoinResultMsg)(nil), "pb.im.GroupJoinResultMsg")
	proto.RegisterType((*TransactionNotificationType)(nil), "pb.im.TransactionNotificationType")
	proto.RegisterType((*TransactionNotificationMsg)(nil), "pb.im.TransactionNotificationMsg")
	proto.RegisterType((*LinkMsg)(nil), "pb.im.LinkMsg")
	proto.RegisterType((*GroupMessageThumbUpMsg)(nil), "pb.im.GroupMessageThumbUpMsg")
}

func init() { proto.RegisterFile("im/im-message.proto", fileDescriptor_a75bf3faa657f674) }

var fileDescriptor_a75bf3faa657f674 = []byte{
	// 1341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xcd, 0x6e, 0xdb, 0xc6,
	0x16, 0xbe, 0xd4, 0x8f, 0x25, 0x1d, 0xc5, 0x36, 0x33, 0x49, 0x7c, 0x15, 0x25, 0xc8, 0x35, 0x78,
	0x83, 0xc6, 0x45, 0x61, 0x0a, 0x70, 0x51, 0x20, 0x68, 0x57, 0x8c, 0x44, 0x2b, 0x4c, 0x24, 0x4a,
	0x25, 0xa9, 0x14, 0xe9, 0xa2, 0xc2, 0x88, 0x1a, 0xc9, 0x8c, 0xc5, 0x19, 0x96, 0x3f, 0x46, 0xb5,
	0xed, 0x33, 0x74, 0xd3, 0x6d, 0xd1, 0x45, 0x5f, 0xa2, 0xdb, 0x2e, 0xfa, 0x04, 0x7d, 0x93, 0x6e,
	0x8b, 0x19, 0x92, 0xfa, 0x6b, 0x9c, 0xd4, 0x59, 0x74, 0x37, 0xdf, 0x99, 0x99, 0x33, 0x67, 0xbe,
	0xf3, 0x9d, 0x33, 0x03, 0x77, 0x3c, 0xbf, 0xe5, 0xf9, 0xa7, 0x3e, 0x89, 0x22, 0x3c, 0x27, 0x6a,
	0x10, 0xb2, 0x98, 0xa1, 0x72, 0x30, 0x51, 0x3d, 0xbf, 0x79, 0x7f, 0xce, 0xd8, 0x7c, 0x41, 0x5a,
	0xc2, 0x38, 0x49, 0x66, 0x2d, 0x4c, 0x97, 0xe9, 0x8a, 0xe6, 0xff, 0x76, 0xa7, 0x62, 0xcf, 0x27,
	0x51, 0x8c, 0xfd, 0x20, 0x5b, 0x70, 0xcf, 0x65, 0x34, 0x8a, 0xa3, 0x96, 0x4b, 0x28, 0x0e, 0xbd,
	0x24, 0x4a, 0xcd, 0xca, 0x1b, 0xa8, 0x19, 0xfd, 0x7e, 0x7a, 0x18, 0x3a, 0x85, 0x52, 0xbc, 0x0c,
	0x48, 0x43, 0x3a, 0x96, 0x4e, 0x0e, 0xce, 0xee, 0xab, 0xe2, 0x54, 0x75, 0x35, 0xef, 0x2c, 0x03,
	0xa2, 0xea, 0x34, 0xf1, 0x2d, 0xb1, 0x0c, 0xa9, 0x50, 0x71, 0x19, 0x8d, 0x09, 0x8d, 0x1b, 0x7b,
	0xc7, 0xd2, 0x49, 0xfd, 0xec, 0xae, 0x9a, 0x46, 0xa1, 0xe6, 0x51, 0xa8, 0x1a, 0x5d, 0x5a, 0xf9,
	0x22, 0xe5, 0x8f, 0x02, 0xec, 0x6f, 0x39, 0x53, 0x7e, 0x2b, 0x40, 0x89, 0x3b, 0x44, 0x75, 0xa8,
	0x8c, 0xcc, 0x97, 0xe6, 0xe0, 0x2b, 0x53, 0xfe, 0x0f, 0xba, 0x05, 0x55, 0xe7, 0xf9, 0xa8, 0xff,
	0x6c, 0x3c, 0x1a, 0xca, 0x12, 0x9f, 0x6a, 0x0f, 0xfa, 0x7d, 0xdd, 0x74, 0xe4, 0x02, 0x42, 0x70,
	0x70, 0x6e, 0x19, 0xba, 0xd9, 0x19, 0x5b, 0xfa, 0x97, 0x23, 0xdd, 0x76, 0xe4, 0x22, 0x7a, 0x00,
	0xff, 0xdd, 0xb6, 0x8d, 0x2d, 0xdd, 0x1e, 0x0e, 0x4c, 0x5b, 0x97, 0x4b, 0xe8, 0x10, 0xea, 0xfd,
	0x01, 0xdf, 0x3c, 0x1e, 0x0e, 0x6c, 0x47, 0x2e, 0x23, 0x19, 0x6e, 0x69, 0xa6, 0x39, 0x18, 0x99,
	0x6d, 0x5d, 0xf8, 0xac, 0xa0, 0x3b, 0x70, 0xd8, 0xd5, 0xfa, 0xfa, 0xd8, 0x30, 0x5f, 0x19, 0x8e,
	0xe6, 0x18, 0x03, 0x53, 0xae, 0xa2, 0x47, 0xd0, 0x5c, 0x39, 0xed, 0x09, 0xa3, 0xfd, 0xdc, 0x18,
	0x8e, 0xdb, 0xcf, 0x35, 0xb3, 0xab, 0xcb, 0x35, 0x74, 0x17, 0xe4, 0xae, 0x35, 0x18, 0x0d, 0x37,
	0x77, 0xc1, 0xda, 0xfa, 0x62, 0x60, 0x98, 0x63, 0x6d, 0x38, 0xec, 0xbd, 0x96, 0xeb, 0xe8, 0x1e,
	0xdc, 0xde, 0xb0, 0x5a, 0xba, 0x3d, 0xea, 0x39, 0xf2, 0x2d, 0xf4, 0x10, 0x1a, 0x8e, 0xa5, 0x99,
	0xb6, 0xd6, 0xe6, 0xbb, 0xc7, 0xe6, 0xc0, 0x31, 0xce, 0x8d, 0x76, 0xea, 0x6a, 0x9f, 0xc7, 0xd9,
	0x33, 0xcc, 0x97, 0xe3, 0xbe, 0x6e, 0xdb, 0x5a, 0x57, 0x97, 0x0f, 0x50, 0x13, 0x8e, 0x52, 0x37,
	0x99, 0x69, 0xbc, 0x22, 0xe9, 0x50, 0x79, 0x05, 0xd5, 0x51, 0x44, 0x42, 0x83, 0xce, 0x18, 0x3a,
	0x82, 0xbd, 0x84, 0x8f, 0xa7, 0x22, 0x8f, 0x45, 0x2b, 0x43, 0xa8, 0x09, 0x55, 0xea, 0xb9, 0x97,
	0x14, 0xfb, 0xa4, 0x51, 0x38, 0x96, 0x4e, 0x6a, 0xd6, 0x0a, 0xf3, 0x3d, 0xf8, 0x0a, 0xc7, 0x38,
	0x6c, 0x14, 0xc5, 0x4c, 0x86, 0x94, 0x1f, 0x25, 0xd8, 0x77, 0x70, 0x38, 0x27, 0xb1, 0x9d, 0xf8,
	0x3e, 0x0e, 0x97, 0xe8, 0x73, 0x00, 0x36, 0x79, 0x43, 0xdc, 0xd8, 0x59, 0x2b, 0xa5, 0xc9, 0x95,
	0x92, 0xea, 0x4b, 0x1d, 0xac, 0x26, 0x53, 0xa9, 0x6c, 0xac, 0xe6, 0x11, 0xa4, 0xc8, 0x98, 0xe6,
	0x11, 0xe4, 0x18, 0x21, 0x28, 0xc5, 0xe4, 0xbb, 0x38, 0x3b, 0x5f, 0x8c, 0xd1, 0x43, 0xa8, 0x79,
	0x3e, 0x9e, 0x93, 0x51, 0xb8, 0x88, 0x1a, 0xa5, 0xe3, 0xe2, 0x49, 0xcd, 0x5a, 0x1b, 0x94, 0x3f,
	0x25, 0x00, 0xe7, 0x22, 0xf1, 0x83, 0x51, 0xd0, 0x8f, 0xe6, 0xe8, 0x09, 0xec, 0x45, 0x84, 0x4e,
	0x49, 0x28, 0x82, 0xaa, 0x9f, 0x1d, 0x66, 0xf2, 0xcd, 0x79, 0xb1, 0xb2, 0x69, 0xf4, 0x14, 0x6a,
	0x6e, 0x48, 0x70, 0x4c, 0xa6, 0x5a, 0x2c, 0xc2, 0xa8, 0x9f, 0x35, 0xff, 0x26, 0x5c, 0x27, 0x2f,
	0x1f, 0x6b, 0xbd, 0x78, 0xe7, 0xee, 0xc5, 0x0f, 0xbe, 0x7b, 0x69, 0xe7, 0xee, 0x2a, 0x54, 0xa2,
	0x94, 0xde, 0x46, 0x39, 0x2b, 0xa4, 0x34, 0xf6, 0x2d, 0xea, 0xad, 0x7c, 0x91, 0xf2, 0x6b, 0x01,
	0xa0, 0xcd, 0x7c, 0x9f, 0xd0, 0xf8, 0x5f, 0xba, 0x79, 0x63, 0x5d, 0xea, 0x69, 0x82, 0x72, 0xb8,
	0xc3, 0x49, 0xe9, 0x83, 0x39, 0x29, 0x5f, 0xcf, 0xc9, 0xde, 0x3f, 0xe0, 0x04, 0xc9, 0x50, 0x9c,
	0x11, 0xd2, 0xa8, 0x08, 0x37, 0x7c, 0xc8, 0x63, 0x0e, 0x49, 0xb0, 0x58, 0x3a, 0xac, 0x51, 0x4d,
	0x63, 0xce, 0xa0, 0x62, 0x83, 0x7c, 0x1e, 0x7a, 0x84, 0x4e, 0x2d, 0xf2, 0x6d, 0x42, 0xa2, 0x9b,
	0x91, 0x78, 0x04, 0x7b, 0x21, 0xc1, 0x11, 0xa3, 0x99, 0x84, 0x33, 0xa4, 0x8c, 0xa1, 0xb1, 0xe5,
	0xd4, 0x22, 0x51, 0xc0, 0x68, 0x44, 0x6e, 0xe4, 0xbc, 0x09, 0x55, 0xec, 0xba, 0x24, 0x88, 0x49,
	0x5a, 0x21, 0x55, 0x6b, 0x85, 0x95, 0xa7, 0xb0, 0xdf, 0x67, 0x3c, 0xe7, 0x43, 0x76, 0xb3, 0x90,
	0x95, 0x4f, 0xe0, 0x50, 0xa3, 0x94, 0x25, 0xd4, 0x25, 0xb9, 0x66, 0x36, 0x12, 0x2a, 0x6d, 0x25,
	0x54, 0xf9, 0x41, 0x82, 0xdb, 0x5d, 0xec, 0x13, 0x83, 0x5e, 0x79, 0x31, 0x8e, 0x3d, 0x46, 0x6f,
	0x4c, 0x0f, 0x63, 0xfe, 0xaa, 0xc2, 0x33, 0x84, 0x1e, 0x01, 0xe0, 0x28, 0x22, 0xb1, 0xed, 0xb2,
	0x30, 0xad, 0x9d, 0xb2, 0xb5, 0x61, 0x59, 0xcd, 0xf7, 0xc8, 0x15, 0x59, 0x64, 0x15, 0xb2, 0x61,
	0x51, 0x7e, 0x91, 0xe0, 0x41, 0xce, 0xef, 0x42, 0x84, 0x15, 0x5d, 0x78, 0x41, 0xfb, 0x02, 0xd3,
	0xb9, 0xa0, 0x58, 0xdb, 0x7a, 0xbb, 0x4e, 0xb3, 0xf0, 0xde, 0xb1, 0x43, 0x4d, 0x47, 0x5c, 0x88,
	0xd9, 0x7b, 0xb6, 0x6e, 0x9c, 0x85, 0xcd, 0xc6, 0xa9, 0xa8, 0x00, 0xeb, 0xb5, 0xdb, 0x4f, 0x55,
	0x05, 0x8a, 0x5a, 0xa7, 0x23, 0x4b, 0x08, 0x60, 0xaf, 0xa3, 0xf7, 0x74, 0x47, 0x97, 0x0b, 0xca,
	0x4f, 0x12, 0xa0, 0x6e, 0xc8, 0x92, 0x60, 0x9b, 0x42, 0x04, 0x25, 0xd1, 0x7b, 0x53, 0xbe, 0xc5,
	0x98, 0x77, 0x38, 0x9f, 0xf8, 0x13, 0x12, 0x9a, 0x89, 0x2f, 0x4e, 0x2d, 0x5b, 0x6b, 0x83, 0x50,
	0x30, 0xa6, 0x97, 0x1e, 0x9d, 0xe7, 0x55, 0x97, 0x41, 0x3e, 0x33, 0x17, 0x27, 0xe4, 0xcd, 0x24,
	0x87, 0xe8, 0x23, 0x38, 0x10, 0x43, 0x4d, 0x34, 0xf0, 0x51, 0xb8, 0xc8, 0x2a, 0x6b, 0xc7, 0xaa,
	0x7c, 0x5f, 0x80, 0xdb, 0x22, 0xc8, 0x17, 0xcc, 0xa3, 0x5a, 0x10, 0x2c, 0x96, 0x3c, 0xc6, 0x8f,
	0xa1, 0x82, 0x83, 0x60, 0xe1, 0x5d, 0x9f, 0xe7, 0x7c, 0x1e, 0xa9, 0x50, 0x4b, 0xcf, 0xa4, 0x33,
	0x96, 0x35, 0x13, 0x39, 0x5b, 0xdc, 0xcd, 0xed, 0xd6, 0x7a, 0x09, 0x3a, 0x81, 0x43, 0x8f, 0xf3,
	0xc1, 0x42, 0xd3, 0x73, 0x2f, 0x4d, 0xce, 0x44, 0x7a, 0xa9, 0x5d, 0x33, 0xbf, 0xdc, 0x05, 0x8e,
	0x86, 0xd8, 0x4b, 0x2f, 0x57, 0xb5, 0x72, 0xc8, 0x7d, 0x60, 0xd7, 0xd5, 0x7c, 0x96, 0xd0, 0xd8,
	0x8e, 0x43, 0x4e, 0x4c, 0x7a, 0xbb, 0x5d, 0x33, 0x7a, 0x0c, 0xfb, 0x22, 0x50, 0x57, 0xd0, 0x6f,
	0x4c, 0x45, 0x13, 0xa9, 0x59, 0xdb, 0x46, 0xc5, 0x86, 0xda, 0x2a, 0xd6, 0x4d, 0x4e, 0xa5, 0x6d,
	0x4e, 0xf3, 0xcc, 0x15, 0x36, 0x32, 0xd7, 0x80, 0xca, 0x0c, 0xbb, 0xfc, 0x25, 0xca, 0x73, 0x93,
	0x41, 0xe5, 0xe7, 0x3c, 0xfd, 0x9c, 0x59, 0x8b, 0x44, 0xc9, 0x42, 0x54, 0xdc, 0x16, 0x5f, 0xd2,
	0xfb, 0xf9, 0x7a, 0x47, 0x2b, 0xd8, 0x64, 0xa8, 0xf8, 0x5e, 0x86, 0x4a, 0x6f, 0x65, 0x48, 0x71,
	0xe0, 0x81, 0x13, 0x62, 0x1a, 0x61, 0x97, 0x93, 0x61, 0xb2, 0xd8, 0x9b, 0x65, 0xc4, 0x88, 0xaf,
	0xd9, 0x67, 0x6f, 0xfb, 0x99, 0xd5, 0xa1, 0x62, 0xe9, 0x6d, 0xdd, 0x78, 0xa5, 0xcb, 0x12, 0xd7,
	0xfe, 0x50, 0x7b, 0x2d, 0x17, 0xb8, 0xf6, 0x2d, 0xfd, 0x7c, 0x64, 0x76, 0xe4, 0xa2, 0xf2, 0xbb,
	0x04, 0xcd, 0x6b, 0xdc, 0x72, 0x12, 0xfe, 0x0f, 0x25, 0x5e, 0x54, 0xd7, 0x89, 0x4b, 0x4c, 0xa6,
	0xbd, 0x49, 0xbc, 0x6e, 0x19, 0xe3, 0x39, 0x14, 0xdf, 0x14, 0x71, 0x87, 0xd5, 0x37, 0x45, 0x20,
	0xbe, 0x23, 0x0e, 0xf1, 0x94, 0xac, 0xcb, 0x21, 0x83, 0xe8, 0x8b, 0xac, 0x2d, 0x94, 0x45, 0x5b,
	0x78, 0x92, 0xbf, 0x21, 0xd7, 0x5f, 0x7c, 0xe3, 0x83, 0xab, 0x10, 0xa8, 0xf4, 0x3c, 0x7a, 0xc9,
	0x03, 0xbf, 0x0b, 0xe5, 0xd8, 0x8b, 0x17, 0x79, 0xf5, 0xa6, 0x80, 0x0b, 0x63, 0x4a, 0x22, 0x37,
	0x17, 0x06, 0x1f, 0xf3, 0x87, 0x28, 0x59, 0x89, 0x82, 0x0f, 0x79, 0x6b, 0x9b, 0xe1, 0x2b, 0xcf,
	0x65, 0x94, 0xab, 0x25, 0x6b, 0x6d, 0x6b, 0x8b, 0xf2, 0x0d, 0x1c, 0x09, 0x05, 0xe4, 0x3f, 0xe3,
	0x8b, 0xc4, 0x9f, 0xa4, 0x7f, 0x9a, 0x95, 0x24, 0x3b, 0xdb, 0x92, 0xec, 0xf0, 0x78, 0xfc, 0x68,
	0x6e, 0x74, 0xb2, 0xa3, 0x53, 0xc0, 0xad, 0xee, 0x8a, 0x9e, 0xb2, 0x95, 0x82, 0x67, 0x8f, 0xbf,
	0x56, 0xe6, 0x5e, 0xbc, 0xc0, 0xfc, 0x4d, 0xf6, 0x5b, 0x57, 0xc4, 0x8d, 0x59, 0x98, 0x04, 0x2d,
	0xd1, 0x5c, 0x4f, 0x83, 0x49, 0x6b, 0xce, 0x5a, 0x9e, 0x3f, 0xd9, 0x13, 0x3f, 0x80, 0x4f, 0xff,
	0x0a, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x60, 0x58, 0x19, 0x81, 0x0c, 0x00, 0x00,
}
