// Code generated by protoc-gen-go. DO NOT EDIT.
// source: consts/cenarius.proto

package consts

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MomentPostType_Enum int32

const (
	MomentPostType_UNKNOWN MomentPostType_Enum = 0
	// 文本
	MomentPostType_TEXT MomentPostType_Enum = 1
	// 游戏总结
	MomentPostType_SUMMARY MomentPostType_Enum = 2
	// 链接（网页之类的）
	MomentPostType_LINK MomentPostType_Enum = 3
)

var MomentPostType_Enum_name = map[int32]string{
	0: "UNKNOWN",
	1: "TEXT",
	2: "SUMMARY",
	3: "LINK",
}

var MomentPostType_Enum_value = map[string]int32{
	"UNKNOWN": 0,
	"TEXT":    1,
	"SUMMARY": 2,
	"LINK":    3,
}

func (x MomentPostType_Enum) String() string {
	return proto.EnumName(MomentPostType_Enum_name, int32(x))
}

func (MomentPostType_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6505f5e3b4744483, []int{0, 0}
}

type ObjectType_Enum int32

const (
	ObjectType_UNKNOWN ObjectType_Enum = 0
	// 财富圈
	ObjectType_MOMENT ObjectType_Enum = 1
	// 游戏总结
	ObjectType_SUMMARY ObjectType_Enum = 2
	// IM 群消息，只有点赞在用
	ObjectType_GROUP_MESSAGE ObjectType_Enum = 3
	// 评论
	ObjectType_COMMENT ObjectType_Enum = 4
	// 链接（网页之类的）
	ObjectType_LINK ObjectType_Enum = 5
)

var ObjectType_Enum_name = map[int32]string{
	0: "UNKNOWN",
	1: "MOMENT",
	2: "SUMMARY",
	3: "GROUP_MESSAGE",
	4: "COMMENT",
	5: "LINK",
}

var ObjectType_Enum_value = map[string]int32{
	"UNKNOWN":       0,
	"MOMENT":        1,
	"SUMMARY":       2,
	"GROUP_MESSAGE": 3,
	"COMMENT":       4,
	"LINK":          5,
}

func (x ObjectType_Enum) String() string {
	return proto.EnumName(ObjectType_Enum_name, int32(x))
}

func (ObjectType_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6505f5e3b4744483, []int{1, 0}
}

type MissionTargetType_Enum int32

const (
	MissionTargetType_Unknown MissionTargetType_Enum = 0
	// 登陆
	MissionTargetType_Login MissionTargetType_Enum = 1
	// 分享游戏
	MissionTargetType_ShareGame MissionTargetType_Enum = 2
	// 玩游戏
	MissionTargetType_PlayGame MissionTargetType_Enum = 3
	// 玩匹配赛
	MissionTargetType_PlayStandardMatch MissionTargetType_Enum = 4
	// 玩排位塞
	MissionTargetType_PlayRankMatch MissionTargetType_Enum = 5
	// 财富自由
	MissionTargetType_WealthFree MissionTargetType_Enum = 6
	// 排位赛财富自由
	MissionTargetType_WealthFreeInRankMatch MissionTargetType_Enum = 7
	// 净资产值
	MissionTargetType_NetAsset MissionTargetType_Enum = 8
	// 排位赛净资产值
	MissionTargetType_NetAssetInRankMatch MissionTargetType_Enum = 9
	// 与好友组队玩游戏
	MissionTargetType_TeamWithFriendAndPlayStandGame MissionTargetType_Enum = 10
	// 排位赛花费 N 年实现财富自由, 消耗时间比目标值小就算任务完成
	MissionTargetType_RankGameWealthFreeSpendNYear MissionTargetType_Enum = 11
	// 排位赛使用 N 个职业财富自由
	MissionTargetType_RankGameUseDiffRoleWealthFree MissionTargetType_Enum = 12
)

var MissionTargetType_Enum_name = map[int32]string{
	0:  "Unknown",
	1:  "Login",
	2:  "ShareGame",
	3:  "PlayGame",
	4:  "PlayStandardMatch",
	5:  "PlayRankMatch",
	6:  "WealthFree",
	7:  "WealthFreeInRankMatch",
	8:  "NetAsset",
	9:  "NetAssetInRankMatch",
	10: "TeamWithFriendAndPlayStandGame",
	11: "RankGameWealthFreeSpendNYear",
	12: "RankGameUseDiffRoleWealthFree",
}

var MissionTargetType_Enum_value = map[string]int32{
	"Unknown":                        0,
	"Login":                          1,
	"ShareGame":                      2,
	"PlayGame":                       3,
	"PlayStandardMatch":              4,
	"PlayRankMatch":                  5,
	"WealthFree":                     6,
	"WealthFreeInRankMatch":          7,
	"NetAsset":                       8,
	"NetAssetInRankMatch":            9,
	"TeamWithFriendAndPlayStandGame": 10,
	"RankGameWealthFreeSpendNYear":   11,
	"RankGameUseDiffRoleWealthFree":  12,
}

func (x MissionTargetType_Enum) String() string {
	return proto.EnumName(MissionTargetType_Enum_name, int32(x))
}

func (MissionTargetType_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6505f5e3b4744483, []int{2, 0}
}

// 财富圈帖子类型
type MomentPostType struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MomentPostType) Reset()         { *m = MomentPostType{} }
func (m *MomentPostType) String() string { return proto.CompactTextString(m) }
func (*MomentPostType) ProtoMessage()    {}
func (*MomentPostType) Descriptor() ([]byte, []int) {
	return fileDescriptor_6505f5e3b4744483, []int{0}
}

func (m *MomentPostType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MomentPostType.Unmarshal(m, b)
}
func (m *MomentPostType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MomentPostType.Marshal(b, m, deterministic)
}
func (m *MomentPostType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MomentPostType.Merge(m, src)
}
func (m *MomentPostType) XXX_Size() int {
	return xxx_messageInfo_MomentPostType.Size(m)
}
func (m *MomentPostType) XXX_DiscardUnknown() {
	xxx_messageInfo_MomentPostType.DiscardUnknown(m)
}

var xxx_messageInfo_MomentPostType proto.InternalMessageInfo

// 目标类型，用在点赞和评论上
type ObjectType struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectType) Reset()         { *m = ObjectType{} }
func (m *ObjectType) String() string { return proto.CompactTextString(m) }
func (*ObjectType) ProtoMessage()    {}
func (*ObjectType) Descriptor() ([]byte, []int) {
	return fileDescriptor_6505f5e3b4744483, []int{1}
}

func (m *ObjectType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectType.Unmarshal(m, b)
}
func (m *ObjectType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectType.Marshal(b, m, deterministic)
}
func (m *ObjectType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectType.Merge(m, src)
}
func (m *ObjectType) XXX_Size() int {
	return xxx_messageInfo_ObjectType.Size(m)
}
func (m *ObjectType) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectType.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectType proto.InternalMessageInfo

// 任务目标定义，用来区分不同的任务
// NOTE(QuantumGhost): 不要修改这个枚举的字段名！
// 数据库里面存储的是字段名 string，修改了字段名会导致读取出错！
type MissionTargetType struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MissionTargetType) Reset()         { *m = MissionTargetType{} }
func (m *MissionTargetType) String() string { return proto.CompactTextString(m) }
func (*MissionTargetType) ProtoMessage()    {}
func (*MissionTargetType) Descriptor() ([]byte, []int) {
	return fileDescriptor_6505f5e3b4744483, []int{2}
}

func (m *MissionTargetType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MissionTargetType.Unmarshal(m, b)
}
func (m *MissionTargetType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MissionTargetType.Marshal(b, m, deterministic)
}
func (m *MissionTargetType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MissionTargetType.Merge(m, src)
}
func (m *MissionTargetType) XXX_Size() int {
	return xxx_messageInfo_MissionTargetType.Size(m)
}
func (m *MissionTargetType) XXX_DiscardUnknown() {
	xxx_messageInfo_MissionTargetType.DiscardUnknown(m)
}

var xxx_messageInfo_MissionTargetType proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("pb.consts.MomentPostType_Enum", MomentPostType_Enum_name, MomentPostType_Enum_value)
	proto.RegisterEnum("pb.consts.ObjectType_Enum", ObjectType_Enum_name, ObjectType_Enum_value)
	proto.RegisterEnum("pb.consts.MissionTargetType_Enum", MissionTargetType_Enum_name, MissionTargetType_Enum_value)
	proto.RegisterType((*MomentPostType)(nil), "pb.consts.MomentPostType")
	proto.RegisterType((*ObjectType)(nil), "pb.consts.ObjectType")
	proto.RegisterType((*MissionTargetType)(nil), "pb.consts.MissionTargetType")
}

func init() { proto.RegisterFile("consts/cenarius.proto", fileDescriptor_6505f5e3b4744483) }

var fileDescriptor_6505f5e3b4744483 = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xdd, 0x6e, 0xd3, 0x30,
	0x18, 0xdd, 0xfa, 0xb7, 0xf6, 0xdb, 0x8f, 0x5c, 0xa3, 0x0a, 0x21, 0x01, 0x82, 0x5c, 0x20, 0x6e,
	0x58, 0x2e, 0xe0, 0x05, 0x0a, 0x64, 0xd5, 0xb4, 0x39, 0xa9, 0x9a, 0x84, 0x32, 0x6e, 0x90, 0x93,
	0x7c, 0x4b, 0xcd, 0x12, 0x3b, 0xb2, 0x5d, 0xd0, 0xde, 0x86, 0xa7, 0xe0, 0xf9, 0x90, 0x13, 0x6d,
	0xad, 0x04, 0x97, 0xe7, 0x7c, 0xc7, 0xe7, 0x1c, 0xc9, 0x07, 0x66, 0xb9, 0x92, 0xc6, 0x1a, 0x3f,
	0x47, 0xc9, 0xb5, 0xd8, 0x9a, 0xf3, 0x46, 0x2b, 0xab, 0xe8, 0xa4, 0xc9, 0xce, 0xbb, 0x8b, 0x77,
	0x01, 0x67, 0x4c, 0xd5, 0x28, 0xed, 0x52, 0x19, 0x9b, 0xdc, 0x37, 0xe8, 0x7d, 0x80, 0x41, 0x20,
	0xb7, 0x35, 0x3d, 0x86, 0xa3, 0x34, 0xbc, 0x0a, 0xa3, 0x75, 0x48, 0x0e, 0xe8, 0x18, 0x06, 0x49,
	0xf0, 0x35, 0x21, 0x87, 0x8e, 0x8e, 0x53, 0xc6, 0xe6, 0xab, 0x1b, 0xd2, 0x73, 0xf4, 0xf5, 0x65,
	0x78, 0x45, 0xfa, 0x5e, 0x01, 0x10, 0x65, 0x3f, 0x30, 0xef, 0x3c, 0xbe, 0xfc, 0xcf, 0x03, 0x60,
	0xc4, 0x22, 0x16, 0x84, 0xff, 0xb8, 0x4c, 0xe1, 0x74, 0xb1, 0x8a, 0xd2, 0xe5, 0x77, 0x16, 0xc4,
	0xf1, 0x7c, 0x11, 0x90, 0xbe, 0xbb, 0x7f, 0x8a, 0x58, 0x2b, 0x1e, 0x3c, 0xa6, 0x0c, 0xbd, 0x3f,
	0x3d, 0x98, 0x32, 0x61, 0x8c, 0x50, 0x32, 0xe1, 0xba, 0xc4, 0x2e, 0xed, 0x77, 0x6f, 0x2f, 0x4e,
	0xde, 0x49, 0xf5, 0x4b, 0x92, 0x03, 0x3a, 0x81, 0xe1, 0xb5, 0x2a, 0x85, 0x24, 0x87, 0xf4, 0x14,
	0x26, 0xf1, 0x86, 0x6b, 0x5c, 0xf0, 0x1a, 0x49, 0x8f, 0x9e, 0xc0, 0x78, 0x59, 0xf1, 0xfb, 0x16,
	0xf5, 0xe9, 0x0c, 0xa6, 0x0e, 0xc5, 0x96, 0xcb, 0x82, 0xeb, 0x82, 0x71, 0x9b, 0x6f, 0xc8, 0xc0,
	0x95, 0x72, 0xf4, 0x8a, 0xcb, 0xbb, 0x8e, 0x1a, 0xd2, 0x33, 0x80, 0x35, 0xf2, 0xca, 0x6e, 0x2e,
	0x34, 0x22, 0x19, 0xd1, 0x67, 0x30, 0xdb, 0xe1, 0x4b, 0xb9, 0x93, 0x1e, 0xb9, 0x88, 0x10, 0xed,
	0xdc, 0x18, 0xb4, 0x64, 0x4c, 0x9f, 0xc2, 0x93, 0x07, 0xb4, 0x2f, 0x9b, 0x50, 0x0f, 0x5e, 0x26,
	0xc8, 0xeb, 0xb5, 0x70, 0x1e, 0x02, 0x65, 0x31, 0x97, 0xc5, 0x63, 0x99, 0xb6, 0x1f, 0xd0, 0x57,
	0xf0, 0xdc, 0x3d, 0x71, 0x68, 0x97, 0x16, 0x37, 0x28, 0x8b, 0xf0, 0x06, 0xb9, 0x26, 0xc7, 0xf4,
	0x35, 0xbc, 0x78, 0x50, 0xa4, 0x06, 0x3f, 0x8b, 0xdb, 0xdb, 0x95, 0xaa, 0xf6, 0xc4, 0xe4, 0xe4,
	0xe3, 0xdb, 0x6f, 0x6f, 0x4a, 0x61, 0x2b, 0xee, 0xfe, 0xbd, 0xf6, 0x7f, 0x62, 0x6e, 0x95, 0xde,
	0x36, 0x3e, 0x77, 0x95, 0xde, 0x35, 0x99, 0x5f, 0x2a, 0xbf, 0x1b, 0x44, 0x36, 0x6a, 0x27, 0xf2,
	0xfe, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa6, 0xfb, 0x46, 0x8c, 0x3b, 0x02, 0x00, 0x00,
}
