// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/maps.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 游戏地图
type GameMap struct {
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 地图剧本, 每一格的剧本类型
	Scenarios            []*GameMap_Scenario `protobuf:"bytes,2,rep,name=scenarios,proto3" json:"scenarios,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GameMap) Reset()         { *m = GameMap{} }
func (m *GameMap) String() string { return proto.CompactTextString(m) }
func (*GameMap) ProtoMessage()    {}
func (*GameMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_072dee0f892d0878, []int{0}
}

func (m *GameMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameMap.Unmarshal(m, b)
}
func (m *GameMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameMap.Marshal(b, m, deterministic)
}
func (m *GameMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameMap.Merge(m, src)
}
func (m *GameMap) XXX_Size() int {
	return xxx_messageInfo_GameMap.Size(m)
}
func (m *GameMap) XXX_DiscardUnknown() {
	xxx_messageInfo_GameMap.DiscardUnknown(m)
}

var xxx_messageInfo_GameMap proto.InternalMessageInfo

func (m *GameMap) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GameMap) GetScenarios() []*GameMap_Scenario {
	if m != nil {
		return m.Scenarios
	}
	return nil
}

type GameMap_Scenario struct {
	Type                 SCENARIO_TYPE `protobuf:"varint,1,opt,name=type,proto3,enum=pb.common.SCENARIO_TYPE" json:"type,omitempty"`
	Location             int32         `protobuf:"varint,2,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GameMap_Scenario) Reset()         { *m = GameMap_Scenario{} }
func (m *GameMap_Scenario) String() string { return proto.CompactTextString(m) }
func (*GameMap_Scenario) ProtoMessage()    {}
func (*GameMap_Scenario) Descriptor() ([]byte, []int) {
	return fileDescriptor_072dee0f892d0878, []int{0, 0}
}

func (m *GameMap_Scenario) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameMap_Scenario.Unmarshal(m, b)
}
func (m *GameMap_Scenario) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameMap_Scenario.Marshal(b, m, deterministic)
}
func (m *GameMap_Scenario) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameMap_Scenario.Merge(m, src)
}
func (m *GameMap_Scenario) XXX_Size() int {
	return xxx_messageInfo_GameMap_Scenario.Size(m)
}
func (m *GameMap_Scenario) XXX_DiscardUnknown() {
	xxx_messageInfo_GameMap_Scenario.DiscardUnknown(m)
}

var xxx_messageInfo_GameMap_Scenario proto.InternalMessageInfo

func (m *GameMap_Scenario) GetType() SCENARIO_TYPE {
	if m != nil {
		return m.Type
	}
	return SCENARIO_TYPE_S_PB_FIRST_MUST_ZORE
}

func (m *GameMap_Scenario) GetLocation() int32 {
	if m != nil {
		return m.Location
	}
	return 0
}

type MapItem struct {
	// 地图 ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 地图名称
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapItem) Reset()         { *m = MapItem{} }
func (m *MapItem) String() string { return proto.CompactTextString(m) }
func (*MapItem) ProtoMessage()    {}
func (*MapItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_072dee0f892d0878, []int{1}
}

func (m *MapItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapItem.Unmarshal(m, b)
}
func (m *MapItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapItem.Marshal(b, m, deterministic)
}
func (m *MapItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapItem.Merge(m, src)
}
func (m *MapItem) XXX_Size() int {
	return xxx_messageInfo_MapItem.Size(m)
}
func (m *MapItem) XXX_DiscardUnknown() {
	xxx_messageInfo_MapItem.DiscardUnknown(m)
}

var xxx_messageInfo_MapItem proto.InternalMessageInfo

func (m *MapItem) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MapItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*GameMap)(nil), "pb.common.GameMap")
	proto.RegisterType((*GameMap_Scenario)(nil), "pb.common.GameMap.Scenario")
	proto.RegisterType((*MapItem)(nil), "pb.common.MapItem")
}

func init() { proto.RegisterFile("common/maps.proto", fileDescriptor_072dee0f892d0878) }

var fileDescriptor_072dee0f892d0878 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x50, 0x4d, 0x4b, 0x33, 0x31,
	0x10, 0x66, 0xb7, 0x7d, 0xdf, 0x76, 0x47, 0x28, 0x18, 0x2f, 0xcb, 0x7a, 0x59, 0x7a, 0x90, 0x3d,
	0xd8, 0x04, 0xea, 0xc9, 0xa3, 0x4a, 0x91, 0x1e, 0xaa, 0x92, 0xf6, 0xa2, 0x17, 0x99, 0x4d, 0x43,
	0x09, 0x34, 0x99, 0xb0, 0x89, 0x82, 0x7f, 0xc9, 0x5f, 0x29, 0xa4, 0x6b, 0x15, 0xbc, 0xcd, 0x3c,
	0x5f, 0xf3, 0x30, 0x70, 0xaa, 0xc8, 0x5a, 0x72, 0xc2, 0xa2, 0x0f, 0xdc, 0x77, 0x14, 0x89, 0x15,
	0xbe, 0xe5, 0x07, 0xb4, 0x3a, 0xeb, 0x59, 0x45, 0x2e, 0xc4, 0x9e, 0x9f, 0x7e, 0x66, 0x30, 0xba,
	0x47, 0xab, 0x57, 0xe8, 0xd9, 0x04, 0x72, 0xb3, 0x2d, 0xb3, 0x3a, 0x6b, 0x06, 0x32, 0x37, 0x5b,
	0x76, 0x0d, 0x45, 0x50, 0xda, 0x61, 0x67, 0x28, 0x94, 0x79, 0x3d, 0x68, 0x4e, 0xe6, 0xe7, 0xfc,
	0x98, 0xc7, 0x7b, 0x1b, 0x5f, 0xf7, 0x1a, 0xf9, 0xa3, 0xae, 0x36, 0x30, 0xfe, 0x86, 0xd9, 0x25,
	0x0c, 0xe3, 0x87, 0xd7, 0x29, 0x78, 0x32, 0x2f, 0x7f, 0x25, 0xac, 0xef, 0x16, 0x0f, 0x37, 0x72,
	0xf9, 0xf8, 0xba, 0x79, 0x7e, 0x5a, 0xc8, 0xa4, 0x62, 0x15, 0x8c, 0xf7, 0xa4, 0x30, 0x1a, 0x72,
	0x65, 0x5e, 0x67, 0xcd, 0x3f, 0x79, 0xdc, 0xa7, 0x33, 0x18, 0xad, 0xd0, 0x2f, 0xa3, 0xb6, 0x7f,
	0xba, 0x32, 0x18, 0x3a, 0xb4, 0x3a, 0x59, 0x0a, 0x99, 0xe6, 0xdb, 0xe6, 0xe5, 0x62, 0x67, 0xe2,
	0x1e, 0xd3, 0x3d, 0xf1, 0xae, 0x55, 0xa4, 0xee, 0xcd, 0x0b, 0x0c, 0x41, 0xc7, 0x99, 0x6f, 0xc5,
	0x8e, 0xc4, 0xa1, 0x48, 0xfb, 0x3f, 0x3d, 0xe3, 0xea, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x35, 0xf8,
	0xa7, 0x5a, 0x41, 0x01, 0x00, 0x00,
}
