// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game/game_consts.proto

package game

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MarketChangeType_Enum int32

const (
	MarketChangeType_UNKNOWN MarketChangeType_Enum = 0
	// 房租上升
	MarketChangeType_RENT_INCREASE MarketChangeType_Enum = 1
	// 房租下降
	MarketChangeType_RENT_DECREASE MarketChangeType_Enum = 2
	// 股权投资破产清零
	MarketChangeType_EQUITY_BANKRUPT MarketChangeType_Enum = 3
	// 企业投资收入上升
	MarketChangeType_COOP_INCOME_INCREASE MarketChangeType_Enum = 4
	// 企业投资收入下降
	MarketChangeType_COOP_INCOME_DECREASE MarketChangeType_Enum = 5
)

var MarketChangeType_Enum_name = map[int32]string{
	0: "UNKNOWN",
	1: "RENT_INCREASE",
	2: "RENT_DECREASE",
	3: "EQUITY_BANKRUPT",
	4: "COOP_INCOME_INCREASE",
	5: "COOP_INCOME_DECREASE",
}

var MarketChangeType_Enum_value = map[string]int32{
	"UNKNOWN":              0,
	"RENT_INCREASE":        1,
	"RENT_DECREASE":        2,
	"EQUITY_BANKRUPT":      3,
	"COOP_INCOME_INCREASE": 4,
	"COOP_INCOME_DECREASE": 5,
}

func (x MarketChangeType_Enum) String() string {
	return proto.EnumName(MarketChangeType_Enum_name, int32(x))
}

func (MarketChangeType_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f1cae5ef3d78a03a, []int{0, 0}
}

// 市场变化类型，对应 S_MARKET_CHANGE
// 注意，这里没有记录对应的变化是影响当前玩家还是所有玩家
// 这个数据有 scenario 模型来做记录
type MarketChangeType struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketChangeType) Reset()         { *m = MarketChangeType{} }
func (m *MarketChangeType) String() string { return proto.CompactTextString(m) }
func (*MarketChangeType) ProtoMessage()    {}
func (*MarketChangeType) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1cae5ef3d78a03a, []int{0}
}

func (m *MarketChangeType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketChangeType.Unmarshal(m, b)
}
func (m *MarketChangeType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketChangeType.Marshal(b, m, deterministic)
}
func (m *MarketChangeType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketChangeType.Merge(m, src)
}
func (m *MarketChangeType) XXX_Size() int {
	return xxx_messageInfo_MarketChangeType.Size(m)
}
func (m *MarketChangeType) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketChangeType.DiscardUnknown(m)
}

var xxx_messageInfo_MarketChangeType proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("pb.game.MarketChangeType_Enum", MarketChangeType_Enum_name, MarketChangeType_Enum_value)
	proto.RegisterType((*MarketChangeType)(nil), "pb.game.MarketChangeType")
}

func init() { proto.RegisterFile("game/game_consts.proto", fileDescriptor_f1cae5ef3d78a03a) }

var fileDescriptor_f1cae5ef3d78a03a = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0x4f, 0xcc, 0x4d,
	0xd5, 0x07, 0x11, 0xf1, 0xc9, 0xf9, 0x79, 0xc5, 0x25, 0xc5, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9,
	0x42, 0xec, 0x05, 0x49, 0x7a, 0x20, 0x51, 0xa5, 0xe9, 0x8c, 0x5c, 0x02, 0xbe, 0x89, 0x45, 0xd9,
	0xa9, 0x25, 0xce, 0x19, 0x89, 0x79, 0xe9, 0xa9, 0x21, 0x95, 0x05, 0xa9, 0x4a, 0x4d, 0x8c, 0x5c,
	0x2c, 0xae, 0x79, 0xa5, 0xb9, 0x42, 0xdc, 0x5c, 0xec, 0xa1, 0x7e, 0xde, 0x7e, 0xfe, 0xe1, 0x7e,
	0x02, 0x0c, 0x42, 0x82, 0x5c, 0xbc, 0x41, 0xae, 0x7e, 0x21, 0xf1, 0x9e, 0x7e, 0xce, 0x41, 0xae,
	0x8e, 0xc1, 0xae, 0x02, 0x8c, 0x70, 0x21, 0x17, 0x57, 0xa8, 0x10, 0x93, 0x90, 0x30, 0x17, 0xbf,
	0x6b, 0x60, 0xa8, 0x67, 0x48, 0x64, 0xbc, 0x93, 0xa3, 0x9f, 0x77, 0x50, 0x68, 0x40, 0x88, 0x00,
	0xb3, 0x90, 0x04, 0x97, 0x88, 0xb3, 0xbf, 0x7f, 0x00, 0x48, 0xab, 0xbf, 0xaf, 0x2b, 0xc2, 0x04,
	0x16, 0x74, 0x19, 0xb8, 0x41, 0xac, 0x4e, 0x6a, 0x51, 0x2a, 0xe9, 0x99, 0x25, 0x39, 0x89, 0x49,
	0x7a, 0xc9, 0xf9, 0xb9, 0xfa, 0x65, 0xa9, 0xc9, 0x25, 0xf9, 0x45, 0xa5, 0x05, 0xfa, 0x89, 0xc5,
	0xc5, 0xa9, 0x25, 0xba, 0x05, 0x49, 0xfa, 0xe9, 0xf9, 0x60, 0x7f, 0x25, 0xb1, 0x81, 0x7d, 0x64,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xae, 0x13, 0x6c, 0x02, 0xeb, 0x00, 0x00, 0x00,
}
